//! Generated card-step dispatch — DO NOT EDIT BY HAND.
//!
//! Regenerate with:
//!
//! ```text
//! python3 versions/v0.111.0/rust/tools/generate_content.py
//! ```
//!
//! PORT_PLAN.md D4. This file is the **complete** dispatch surface: one arm
//! per StepKind variant (334 of them), each delegating to a body in the
//! per-family module that owns it. It is generated once and never edited by a
//! wave PR, so two wave PRs cannot conflict here; a wave PR replaces a stub
//! body in its own `steps/<family>.rs` and flips nothing shared.
//!
//! The family split is derived, not assigned:
//! a kind belongs to the `content/cards/*.py` family whose cards use it,
//! `templates` when only auto-translated `card_templates.json` rows use it,
//! and `shared` when more than one family does.
//!
//! Freshness (this file, and the existence of every dispatch target) is
//! CI-enforced by the `rust port` workflow's generator `--check` step.

pub mod block_next;
pub mod calculated_history;
pub mod curses;
pub mod defect_common;
pub mod defect_orb;
pub mod defect_rare;
pub mod defect_uncommon;
pub mod hand_cap;
pub mod ironclad_common;
pub mod ironclad_rare;
pub mod ironclad_uncommon;
pub mod necrobinder_common;
pub mod necrobinder_osty;
pub mod necrobinder_rare;
pub mod necrobinder_uncommon;
pub mod neutral;
pub mod physical_cost;
pub mod physical_lifecycle;
pub mod regent_ancient;
pub mod regent_forge;
pub mod regent_uncommon;
pub mod resource_powers;
pub mod same_turn_history;
pub mod shared;
pub mod silent_rare;
pub mod silent_special;
pub mod silent_uncommon;
pub mod single_pile_selection;
pub mod status;
pub mod templates;

use crate::engine::{EngineRefusal, StepCtx};
use crate::ids::StepKind;

/// Every StepKind, with the family module that owns its body.
///
/// Published so the completeness/uniqueness contract test can be
/// derived rather than hand-listed.
#[rustfmt::skip]
pub static FAMILY_OF: [(StepKind, &str); 334] = [
    (StepKind::AbundanceExact, "neutral"), (StepKind::Accelerant, "templates"),
    (StepKind::Accuracy, "templates"), (StepKind::ActiveCardCostAddExact, "defect_rare"),
    (StepKind::AdaptiveStrikeExact, "defect_rare"), (StepKind::AddOrbSlotsExact, "shared"),
    (StepKind::Afterimage, "templates"), (StepKind::Aggression, "templates"),
    (StepKind::AlchemizeExact, "neutral"), (StepKind::AllForOneExact, "defect_rare"),
    (StepKind::AngerExact, "ironclad_common"), (StepKind::Arsenal, "templates"),
    (StepKind::Attack, "shared"), (StepKind::AttackAll, "shared"),
    (StepKind::AttackAllTempStrengthSnapshot, "shared"), (StepKind::AttackAllX,
    "ironclad_uncommon"), (StepKind::AttackContextResultExact, "shared"),
    (StepKind::AttackPerStrike, "ironclad_common"), (StepKind::AttackPerVuln,
    "ironclad_uncommon"), (StepKind::AttackRandom, "shared"), (StepKind::AttackRandomX,
    "shared"), (StepKind::AttackResult, "shared"), (StepKind::AttackX, "shared"),
    (StepKind::Automation, "templates"), (StepKind::AutoplayDrawX, "ironclad_rare"),
    (StepKind::Barricade, "templates"), (StepKind::BeaconOfHopeExact, "neutral"),
    (StepKind::BeatDownExact, "neutral"), (StepKind::BelieveInYouExact, "neutral"),
    (StepKind::BiasedCognition, "templates"), (StepKind::BlackHole, "templates"),
    (StepKind::BladeSymphonyExact, "silent_uncommon"), (StepKind::BlazeExact,
    "ironclad_uncommon"), (StepKind::Block, "shared"), (StepKind::BlockNextBody, "block_next"),
    (StepKind::Blur, "templates"), (StepKind::BorrowedTime, "templates"),
    (StepKind::BrightestFlameExact, "neutral"), (StepKind::Buffer, "templates"),
    (StepKind::BulletTimeExact, "silent_rare"), (StepKind::BundleOfJoyExact, "regent_uncommon"),
    (StepKind::Burst, "templates"), (StepKind::Cacophony, "templates"),
    (StepKind::CalamityExact, "neutral"), (StepKind::Calcify, "shared"),
    (StepKind::CalculatedAttack, "shared"), (StepKind::CalculatedBlock, "shared"),
    (StepKind::CalculatedDoomExact, "necrobinder_uncommon"), (StepKind::CalculatedHits,
    "shared"), (StepKind::CallOfTheVoid, "necrobinder_rare"), (StepKind::CatastropheExact,
    "neutral"), (StepKind::Channel, "shared"), (StepKind::ChannelHittableSnapshot,
    "defect_orb"), (StepKind::ChannelVoltaic, "defect_orb"), (StepKind::ChannelX, "defect_orb"),
    (StepKind::ChildOfTheStars, "templates"), (StepKind::ClawExact, "physical_cost"),
    (StepKind::Colossus, "templates"), (StepKind::CompactExact, "defect_uncommon"),
    (StepKind::CompileDriverUniqueOrbExact, "defect_orb"), (StepKind::ConcoctExact,
    "silent_uncommon"), (StepKind::ConstellationExact, "regent_uncommon"),
    (StepKind::ConsumingShadowExact, "defect_rare"), (StepKind::Coolant, "templates"),
    (StepKind::CoordinateExact, "neutral"), (StepKind::CorrosiveWave, "templates"),
    (StepKind::Corruption, "templates"), (StepKind::Countdown, "templates"),
    (StepKind::CreativeAi, "defect_rare"), (StepKind::CrescentSpearExact, "calculated_history"),
    (StepKind::CrimsonMantle, "ironclad_rare"), (StepKind::Cruelty, "templates"),
    (StepKind::DanseMacabre, "templates"), (StepKind::DarkEmbrace, "templates"),
    (StepKind::Darkness, "defect_orb"), (StepKind::DeathsDoorExact, "necrobinder_uncommon"),
    (StepKind::Debilitate, "templates"), (StepKind::Demesne, "templates"), (StepKind::DemonForm,
    "templates"), (StepKind::DemonicShieldBlockExact, "ironclad_uncommon"),
    (StepKind::DevourLife, "templates"), (StepKind::Dexterity, "shared"),
    (StepKind::DirgeXExact, "necrobinder_uncommon"), (StepKind::DiscardHandDraw,
    "ironclad_uncommon"), (StepKind::DiscoveryExact, "neutral"), (StepKind::DistractionExact,
    "silent_special"), (StepKind::Doom, "templates"), (StepKind::DrainPowerExact,
    "necrobinder_common"), (StepKind::Draw, "shared"), (StepKind::DrawIfNoHandAttacks,
    "neutral"), (StepKind::DrawNextTurn, "templates"), (StepKind::DrumOfBattleExact,
    "ironclad_uncommon"), (StepKind::EchoForm, "templates"), (StepKind::EidolonExact,
    "neutral"), (StepKind::EndOfDaysExact, "necrobinder_rare"), (StepKind::Energy, "shared"),
    (StepKind::EnergyNextTurn, "shared"), (StepKind::EnergySurgeExact, "defect_uncommon"),
    (StepKind::EnlightenmentExact, "neutral"), (StepKind::Entropy, "templates"),
    (StepKind::Envenom, "templates"), (StepKind::EscapePlanExact, "silent_uncommon"),
    (StepKind::EvokeFrontExact, "defect_orb"), (StepKind::EvokeFrontX, "defect_orb"),
    (StepKind::ExhaustDraw, "ironclad_uncommon"), (StepKind::ExhaustNonattacksBlock,
    "ironclad_uncommon"), (StepKind::ExhaustRandom, "ironclad_common"),
    (StepKind::ExpertiseExact, "silent_uncommon"), (StepKind::ExposeExact, "silent_uncommon"),
    (StepKind::FadeExact, "silent_uncommon"), (StepKind::FanOfKnivesExact, "silent_rare"),
    (StepKind::Fasten, "templates"), (StepKind::FatalAttackRewardExact, "shared"),
    (StepKind::FeelNoPain, "templates"), (StepKind::Feral, "physical_lifecycle"),
    (StepKind::FiendFireExact, "ironclad_rare"), (StepKind::FlakCannonExact, "defect_rare"),
    (StepKind::FlameBarrier, "templates"), (StepKind::FlankingExact, "silent_rare"),
    (StepKind::Focus, "templates"), (StepKind::Foregone, "templates"),
    (StepKind::ForgeFamilyExact, "regent_forge"), (StepKind::ForgottenRitualEnergyExact,
    "same_turn_history"), (StepKind::FranticEscapeExact, "status"), (StepKind::FreeAttack,
    "templates"), (StepKind::FreeEthereal, "templates"), (StepKind::FreePower, "templates"),
    (StepKind::FreeSkill, "templates"), (StepKind::FriendshipExact, "resource_powers"),
    (StepKind::Furnace, "regent_forge"), (StepKind::GainCurrentBlockCardUnpoweredExact,
    "neutral"), (StepKind::GainCurrentEnergyExact, "defect_uncommon"), (StepKind::GangUpExact,
    "neutral"), (StepKind::GenerateFixedShivs, "shared"), (StepKind::GenerateFixedStatus,
    "shared"), (StepKind::GenerateShivsThenInkyExact, "silent_rare"),
    (StepKind::GenerateShivsThenUpgradeExact, "silent_uncommon"), (StepKind::Genesis,
    "templates"), (StepKind::GeneticAlgorithmBlockExact, "defect_rare"),
    (StepKind::GeneticAlgorithmGrowthExact, "defect_rare"), (StepKind::GlimmerExact,
    "single_pile_selection"), (StepKind::GlimpseBeyondExact, "necrobinder_rare"),
    (StepKind::GoForTheEyesExact, "defect_common"), (StepKind::GuidingStarDrawNextTurnExact,
    "regent_uncommon"), (StepKind::GunkUpExact, "defect_common"), (StepKind::Hailstorm,
    "templates"), (StepKind::HammerTimeExact, "regent_forge"), (StepKind::HandCapBody,
    "hand_cap"), (StepKind::HangExact, "necrobinder_rare"), (StepKind::HauntPower, "shared"),
    (StepKind::Havoc, "ironclad_common"), (StepKind::Heal, "shared"), (StepKind::HeavenlyDrillX,
    "ironclad_rare"), (StepKind::HelixDrillExact, "calculated_history"), (StepKind::HelloWorld,
    "templates"), (StepKind::Hellraiser, "templates"), (StepKind::HibernatePowerExact,
    "defect_uncommon"), (StepKind::HiddenGemExact, "neutral"), (StepKind::HpLoss, "shared"),
    (StepKind::HuddleUpExact, "regent_uncommon"), (StepKind::HyperbeamFocusDownExact,
    "defect_orb"), (StepKind::IgnitionExact, "defect_uncommon"),
    (StepKind::ImitationLearningExact, "defect_rare"), (StepKind::InfernalBladeExact,
    "ironclad_uncommon"), (StepKind::Inferno, "ironclad_uncommon"), (StepKind::InfiniteBlades,
    "templates"), (StepKind::Intangible, "templates"), (StepKind::InterceptExact, "neutral"),
    (StepKind::Iteration, "templates"), (StepKind::JackOfAllTradesExact, "neutral"),
    (StepKind::JackpotExact, "neutral"), (StepKind::Juggernaut, "templates"),
    (StepKind::JugglingExact, "ironclad_uncommon"), (StepKind::KnifeTrapExact, "silent_rare"),
    (StepKind::Knockdown, "templates"), (StepKind::LargesseExact, "regent_uncommon"),
    (StepKind::LegionOfBoneExact, "necrobinder_uncommon"), (StepKind::Lethality, "shared"),
    (StepKind::LiftExact, "neutral"), (StepKind::LightningRod, "defect_orb"), (StepKind::Loop,
    "templates"), (StepKind::MachineLearning, "templates"), (StepKind::MadScienceChaosExact,
    "neutral"), (StepKind::MalaiseX, "silent_rare"), (StepKind::ManifestAuthorityExact,
    "regent_uncommon"), (StepKind::MasterPlanner, "physical_lifecycle"), (StepKind::MaulExact,
    "physical_cost"), (StepKind::Mayhem, "templates"), (StepKind::MetamorphosisExact,
    "neutral"), (StepKind::MeteorShowerExact, "regent_ancient"), (StepKind::MimicExact,
    "neutral"), (StepKind::MirageTotalPoisonBlockExact, "silent_uncommon"),
    (StepKind::MiseryExact, "necrobinder_rare"), (StepKind::MoltenVuln, "ironclad_common"),
    (StepKind::MomentumStrikeExact, "physical_cost"), (StepKind::MonarchsGaze, "templates"),
    (StepKind::Monologue, "regent_uncommon"), (StepKind::NecroMastery, "templates"),
    (StepKind::Neurosurge, "templates"), (StepKind::NoDraw, "templates"), (StepKind::Nostalgia,
    "neutral"), (StepKind::NoxiousFumes, "templates"), (StepKind::Oblivion, "templates"),
    (StepKind::OneForAllExact, "defect_rare"), (StepKind::OneTwoPunch, "templates"),
    (StepKind::Orbit, "templates"), (StepKind::OstyBody, "necrobinder_osty"),
    (StepKind::OstySummonHeal, "necrobinder_osty"), (StepKind::OutbreakExact, "silent_rare"),
    (StepKind::OutrageExact, "ironclad_uncommon"), (StepKind::PactsEndExact, "ironclad_rare"),
    (StepKind::Pagestorm, "templates"), (StepKind::PaleBlueDot, "templates"),
    (StepKind::Panache, "templates"), (StepKind::PanicButtonExact, "neutral"), (StepKind::Parry,
    "regent_forge"), (StepKind::PhantomBlades, "templates"), (StepKind::PhysicalDamageAttack,
    "physical_cost"), (StepKind::PillageExact, "silent_uncommon"), (StepKind::PillarOfCreation,
    "templates"), (StepKind::Plating, "templates"), (StepKind::PlotExact, "regent_uncommon"),
    (StepKind::Poison, "templates"), (StepKind::PoisonIfPoisoned, "silent_uncommon"),
    (StepKind::PoisonRandomSerial, "silent_uncommon"), (StepKind::PowerAllSerial, "shared"),
    (StepKind::PrepTime, "templates"), (StepKind::PrimalForceExact, "ironclad_rare"),
    (StepKind::PullFromBelowExact, "calculated_history"), (StepKind::PurityExact, "neutral"),
    (StepKind::Pyre, "templates"), (StepKind::QuasarExact, "regent_uncommon"),
    (StepKind::RadiateExact, "calculated_history"), (StepKind::Rage, "templates"),
    (StepKind::RallyExact, "neutral"), (StepKind::RampageExact, "physical_cost"),
    (StepKind::RandomOrbLoopExact, "defect_uncommon"), (StepKind::RattleExact,
    "calculated_history"), (StepKind::ReaperForm, "templates"), (StepKind::RebootShuffleExact,
    "defect_rare"), (StepKind::Rebound, "neutral"), (StepKind::Reflect, "templates"),
    (StepKind::RemoveOrbSlotsExact, "defect_orb"), (StepKind::RendExact, "neutral"),
    (StepKind::RestlessnessExact, "neutral"), (StepKind::RetainHand, "templates"),
    (StepKind::RollingBoulder, "templates"), (StepKind::Rupture, "templates"),
    (StepKind::SacrificeOstyExact, "necrobinder_osty"), (StepKind::SameTurnHistoryBody,
    "same_turn_history"), (StepKind::ScrapeExact, "defect_uncommon"), (StepKind::SealedThrone,
    "templates"), (StepKind::SeekerStrikeExact, "neutral"), (StepKind::Select, "shared"),
    (StepKind::SentryMode, "templates"), (StepKind::SerpentForm, "shared"),
    (StepKind::ShadowStepDiscardExact, "silent_rare"), (StepKind::ShadowStepPowerExact,
    "silent_rare"), (StepKind::Shadowmeld, "shared"), (StepKind::SharedFateExact,
    "necrobinder_rare"), (StepKind::ShatterOrbsExact, "defect_orb"), (StepKind::ShivAttack,
    "silent_special"), (StepKind::ShockwaveExact, "ironclad_uncommon"), (StepKind::Shroud,
    "shared"), (StepKind::SicEmExact, "necrobinder_osty"), (StepKind::SignalBoost, "templates"),
    (StepKind::SleightOfFlesh, "templates"), (StepKind::Smokestack, "templates"),
    (StepKind::Sneaky, "templates"), (StepKind::SoulBody, "shared"), (StepKind::SoulboundExact,
    "necrobinder_uncommon"), (StepKind::SovereignBladeExact, "regent_forge"),
    (StepKind::SpectrumShift, "shared"), (StepKind::Speedster, "templates"), (StepKind::Spinner,
    "shared"), (StepKind::SpiritOfAsh, "templates"), (StepKind::SplashExact, "neutral"),
    (StepKind::Stampede, "templates"), (StepKind::StarNextTurn, "templates"), (StepKind::Stars,
    "shared"), (StepKind::StokeExact, "ironclad_rare"), (StepKind::StompExact,
    "ironclad_uncommon"), (StepKind::Storm, "defect_orb"), (StepKind::StormOfSteelExact,
    "silent_rare"), (StepKind::Strangle, "templates"), (StepKind::Stratagem, "templates"),
    (StepKind::Strength, "shared"), (StepKind::StrengthEnemy, "templates"),
    (StepKind::StunTarget, "neutral"), (StepKind::Subroutine, "templates"), (StepKind::Summon,
    "shared"), (StepKind::SummonNextTurn, "templates"), (StepKind::SwordSage, "regent_forge"),
    (StepKind::SynchronizeUniqueOrbFocusExact, "defect_orb"), (StepKind::TagTeamExact,
    "neutral"), (StepKind::TankExact, "ironclad_rare"), (StepKind::TearAsunderExact,
    "calculated_history"), (StepKind::TempDexterity, "templates"), (StepKind::TempFocus,
    "defect_orb"), (StepKind::TempStrength, "shared"), (StepKind::TempStrengthEnemy,
    "templates"), (StepKind::TeslaCoil, "defect_orb"), (StepKind::TheBallExact, "neutral"),
    (StepKind::TheBombExact, "neutral"), (StepKind::TheGambit, "templates"),
    (StepKind::TheHuntExact, "silent_rare"), (StepKind::TheScytheExact, "necrobinder_rare"),
    (StepKind::Thorns, "templates"), (StepKind::ThrashExact, "ironclad_rare"),
    (StepKind::Thunder, "defect_orb"), (StepKind::ThunderclapExact, "ironclad_common"),
    (StepKind::ToolsOfTheTrade, "shared"), (StepKind::ToricToughnessExact, "neutral"),
    (StepKind::Tracking, "templates"), (StepKind::TrashToTreasure, "templates"),
    (StepKind::TurnEndGoldLossExact, "curses"), (StepKind::TutorExact, "regent_uncommon"),
    (StepKind::Tyranny, "shared"), (StepKind::UndeathExact, "necrobinder_rare"),
    (StepKind::Underworld, "templates"), (StepKind::Unmovable, "templates"),
    (StepKind::UpMySleeveCostExact, "silent_uncommon"),
    (StepKind::UpgradeAllCombatExceptSourceExact, "neutral"), (StepKind::UpgradeAllHand,
    "ironclad_common"), (StepKind::UproarExact, "defect_common"), (StepKind::Vicious, "shared"),
    (StepKind::Vigor, "templates"), (StepKind::VoidForm, "regent_uncommon"),
    (StepKind::Vulnerable, "shared"), (StepKind::VulnerableThenStrengthCurrent,
    "ironclad_uncommon"), (StepKind::Weak, "shared"), (StepKind::WellLaidPlans,
    "silent_uncommon"), (StepKind::WhiteNoiseExact, "defect_uncommon"), (StepKind::WraithForm,
    "templates"),
];

/// Each family's own implemented-kind registry.
///
/// D6: the capability manifest is DERIVED from these, never
/// transcribed. A family file owns its entry; this table only
/// concatenates them.
#[rustfmt::skip]
pub static FAMILIES: [(&str, &[StepKind]); 30] = [
    ("block_next", block_next::IMPLEMENTED), ("calculated_history",
    calculated_history::IMPLEMENTED), ("curses", curses::IMPLEMENTED), ("defect_common",
    defect_common::IMPLEMENTED), ("defect_orb", defect_orb::IMPLEMENTED), ("defect_rare",
    defect_rare::IMPLEMENTED), ("defect_uncommon", defect_uncommon::IMPLEMENTED), ("hand_cap",
    hand_cap::IMPLEMENTED), ("ironclad_common", ironclad_common::IMPLEMENTED), ("ironclad_rare",
    ironclad_rare::IMPLEMENTED), ("ironclad_uncommon", ironclad_uncommon::IMPLEMENTED),
    ("necrobinder_common", necrobinder_common::IMPLEMENTED), ("necrobinder_osty",
    necrobinder_osty::IMPLEMENTED), ("necrobinder_rare", necrobinder_rare::IMPLEMENTED),
    ("necrobinder_uncommon", necrobinder_uncommon::IMPLEMENTED), ("neutral",
    neutral::IMPLEMENTED), ("physical_cost", physical_cost::IMPLEMENTED), ("physical_lifecycle",
    physical_lifecycle::IMPLEMENTED), ("regent_ancient", regent_ancient::IMPLEMENTED),
    ("regent_forge", regent_forge::IMPLEMENTED), ("regent_uncommon",
    regent_uncommon::IMPLEMENTED), ("resource_powers", resource_powers::IMPLEMENTED),
    ("same_turn_history", same_turn_history::IMPLEMENTED), ("shared", shared::IMPLEMENTED),
    ("silent_rare", silent_rare::IMPLEMENTED), ("silent_special", silent_special::IMPLEMENTED),
    ("silent_uncommon", silent_uncommon::IMPLEMENTED), ("single_pile_selection",
    single_pile_selection::IMPLEMENTED), ("status", status::IMPLEMENTED), ("templates",
    templates::IMPLEMENTED),
];

/// Whether some family implements `kind`.
///
/// Boundary-time work (the admission gate and the manifest), never a
/// per-node path: it walks the family registries.
pub fn is_implemented(kind: StepKind) -> bool {
    FAMILIES.iter().any(|(_, kinds)| kinds.contains(&kind))
}

/// Dispatch one card-step to its family body.
pub fn apply_step(kind: StepKind, ctx: &mut StepCtx<'_>) -> Result<(), EngineRefusal> {
    match kind {
        StepKind::AbundanceExact => neutral::abundance_exact(ctx),
        StepKind::Accelerant => templates::accelerant(ctx),
        StepKind::Accuracy => templates::accuracy(ctx),
        StepKind::ActiveCardCostAddExact => defect_rare::active_card_cost_add_exact(ctx),
        StepKind::AdaptiveStrikeExact => defect_rare::adaptive_strike_exact(ctx),
        StepKind::AddOrbSlotsExact => shared::add_orb_slots_exact(ctx),
        StepKind::Afterimage => templates::afterimage(ctx),
        StepKind::Aggression => templates::aggression(ctx),
        StepKind::AlchemizeExact => neutral::alchemize_exact(ctx),
        StepKind::AllForOneExact => defect_rare::all_for_one_exact(ctx),
        StepKind::AngerExact => ironclad_common::anger_exact(ctx),
        StepKind::Arsenal => templates::arsenal(ctx),
        StepKind::Attack => shared::attack(ctx),
        StepKind::AttackAll => shared::attack_all(ctx),
        StepKind::AttackAllTempStrengthSnapshot => shared::attack_all_temp_strength_snapshot(ctx),
        StepKind::AttackAllX => ironclad_uncommon::attack_all_x(ctx),
        StepKind::AttackContextResultExact => shared::attack_context_result_exact(ctx),
        StepKind::AttackPerStrike => ironclad_common::attack_per_strike(ctx),
        StepKind::AttackPerVuln => ironclad_uncommon::attack_per_vuln(ctx),
        StepKind::AttackRandom => shared::attack_random(ctx),
        StepKind::AttackRandomX => shared::attack_random_x(ctx),
        StepKind::AttackResult => shared::attack_result(ctx),
        StepKind::AttackX => shared::attack_x(ctx),
        StepKind::Automation => templates::automation(ctx),
        StepKind::AutoplayDrawX => ironclad_rare::autoplay_draw_x(ctx),
        StepKind::Barricade => templates::barricade(ctx),
        StepKind::BeaconOfHopeExact => neutral::beacon_of_hope_exact(ctx),
        StepKind::BeatDownExact => neutral::beat_down_exact(ctx),
        StepKind::BelieveInYouExact => neutral::believe_in_you_exact(ctx),
        StepKind::BiasedCognition => templates::biased_cognition(ctx),
        StepKind::BlackHole => templates::black_hole(ctx),
        StepKind::BladeSymphonyExact => silent_uncommon::blade_symphony_exact(ctx),
        StepKind::BlazeExact => ironclad_uncommon::blaze_exact(ctx),
        StepKind::Block => shared::block(ctx),
        StepKind::BlockNextBody => block_next::block_next_body(ctx),
        StepKind::Blur => templates::blur(ctx),
        StepKind::BorrowedTime => templates::borrowed_time(ctx),
        StepKind::BrightestFlameExact => neutral::brightest_flame_exact(ctx),
        StepKind::Buffer => templates::buffer(ctx),
        StepKind::BulletTimeExact => silent_rare::bullet_time_exact(ctx),
        StepKind::BundleOfJoyExact => regent_uncommon::bundle_of_joy_exact(ctx),
        StepKind::Burst => templates::burst(ctx),
        StepKind::Cacophony => templates::cacophony(ctx),
        StepKind::CalamityExact => neutral::calamity_exact(ctx),
        StepKind::Calcify => shared::calcify(ctx),
        StepKind::CalculatedAttack => shared::calculated_attack(ctx),
        StepKind::CalculatedBlock => shared::calculated_block(ctx),
        StepKind::CalculatedDoomExact => necrobinder_uncommon::calculated_doom_exact(ctx),
        StepKind::CalculatedHits => shared::calculated_hits(ctx),
        StepKind::CallOfTheVoid => necrobinder_rare::call_of_the_void(ctx),
        StepKind::CatastropheExact => neutral::catastrophe_exact(ctx),
        StepKind::Channel => shared::channel(ctx),
        StepKind::ChannelHittableSnapshot => defect_orb::channel_hittable_snapshot(ctx),
        StepKind::ChannelVoltaic => defect_orb::channel_voltaic(ctx),
        StepKind::ChannelX => defect_orb::channel_x(ctx),
        StepKind::ChildOfTheStars => templates::child_of_the_stars(ctx),
        StepKind::ClawExact => physical_cost::claw_exact(ctx),
        StepKind::Colossus => templates::colossus(ctx),
        StepKind::CompactExact => defect_uncommon::compact_exact(ctx),
        StepKind::CompileDriverUniqueOrbExact => defect_orb::compile_driver_unique_orb_exact(ctx),
        StepKind::ConcoctExact => silent_uncommon::concoct_exact(ctx),
        StepKind::ConstellationExact => regent_uncommon::constellation_exact(ctx),
        StepKind::ConsumingShadowExact => defect_rare::consuming_shadow_exact(ctx),
        StepKind::Coolant => templates::coolant(ctx),
        StepKind::CoordinateExact => neutral::coordinate_exact(ctx),
        StepKind::CorrosiveWave => templates::corrosive_wave(ctx),
        StepKind::Corruption => templates::corruption(ctx),
        StepKind::Countdown => templates::countdown(ctx),
        StepKind::CreativeAi => defect_rare::creative_ai(ctx),
        StepKind::CrescentSpearExact => calculated_history::crescent_spear_exact(ctx),
        StepKind::CrimsonMantle => ironclad_rare::crimson_mantle(ctx),
        StepKind::Cruelty => templates::cruelty(ctx),
        StepKind::DanseMacabre => templates::danse_macabre(ctx),
        StepKind::DarkEmbrace => templates::dark_embrace(ctx),
        StepKind::Darkness => defect_orb::darkness(ctx),
        StepKind::DeathsDoorExact => necrobinder_uncommon::deaths_door_exact(ctx),
        StepKind::Debilitate => templates::debilitate(ctx),
        StepKind::Demesne => templates::demesne(ctx),
        StepKind::DemonForm => templates::demon_form(ctx),
        StepKind::DemonicShieldBlockExact => ironclad_uncommon::demonic_shield_block_exact(ctx),
        StepKind::DevourLife => templates::devour_life(ctx),
        StepKind::Dexterity => shared::dexterity(ctx),
        StepKind::DirgeXExact => necrobinder_uncommon::dirge_x_exact(ctx),
        StepKind::DiscardHandDraw => ironclad_uncommon::discard_hand_draw(ctx),
        StepKind::DiscoveryExact => neutral::discovery_exact(ctx),
        StepKind::DistractionExact => silent_special::distraction_exact(ctx),
        StepKind::Doom => templates::doom(ctx),
        StepKind::DrainPowerExact => necrobinder_common::drain_power_exact(ctx),
        StepKind::Draw => shared::draw(ctx),
        StepKind::DrawIfNoHandAttacks => neutral::draw_if_no_hand_attacks(ctx),
        StepKind::DrawNextTurn => templates::draw_next_turn(ctx),
        StepKind::DrumOfBattleExact => ironclad_uncommon::drum_of_battle_exact(ctx),
        StepKind::EchoForm => templates::echo_form(ctx),
        StepKind::EidolonExact => neutral::eidolon_exact(ctx),
        StepKind::EndOfDaysExact => necrobinder_rare::end_of_days_exact(ctx),
        StepKind::Energy => shared::energy(ctx),
        StepKind::EnergyNextTurn => shared::energy_next_turn(ctx),
        StepKind::EnergySurgeExact => defect_uncommon::energy_surge_exact(ctx),
        StepKind::EnlightenmentExact => neutral::enlightenment_exact(ctx),
        StepKind::Entropy => templates::entropy(ctx),
        StepKind::Envenom => templates::envenom(ctx),
        StepKind::EscapePlanExact => silent_uncommon::escape_plan_exact(ctx),
        StepKind::EvokeFrontExact => defect_orb::evoke_front_exact(ctx),
        StepKind::EvokeFrontX => defect_orb::evoke_front_x(ctx),
        StepKind::ExhaustDraw => ironclad_uncommon::exhaust_draw(ctx),
        StepKind::ExhaustNonattacksBlock => ironclad_uncommon::exhaust_nonattacks_block(ctx),
        StepKind::ExhaustRandom => ironclad_common::exhaust_random(ctx),
        StepKind::ExpertiseExact => silent_uncommon::expertise_exact(ctx),
        StepKind::ExposeExact => silent_uncommon::expose_exact(ctx),
        StepKind::FadeExact => silent_uncommon::fade_exact(ctx),
        StepKind::FanOfKnivesExact => silent_rare::fan_of_knives_exact(ctx),
        StepKind::Fasten => templates::fasten(ctx),
        StepKind::FatalAttackRewardExact => shared::fatal_attack_reward_exact(ctx),
        StepKind::FeelNoPain => templates::feel_no_pain(ctx),
        StepKind::Feral => physical_lifecycle::feral(ctx),
        StepKind::FiendFireExact => ironclad_rare::fiend_fire_exact(ctx),
        StepKind::FlakCannonExact => defect_rare::flak_cannon_exact(ctx),
        StepKind::FlameBarrier => templates::flame_barrier(ctx),
        StepKind::FlankingExact => silent_rare::flanking_exact(ctx),
        StepKind::Focus => templates::focus(ctx),
        StepKind::Foregone => templates::foregone(ctx),
        StepKind::ForgeFamilyExact => regent_forge::forge_family_exact(ctx),
        StepKind::ForgottenRitualEnergyExact => {
            same_turn_history::forgotten_ritual_energy_exact(ctx)
        }
        StepKind::FranticEscapeExact => status::frantic_escape_exact(ctx),
        StepKind::FreeAttack => templates::free_attack(ctx),
        StepKind::FreeEthereal => templates::free_ethereal(ctx),
        StepKind::FreePower => templates::free_power(ctx),
        StepKind::FreeSkill => templates::free_skill(ctx),
        StepKind::FriendshipExact => resource_powers::friendship_exact(ctx),
        StepKind::Furnace => regent_forge::furnace(ctx),
        StepKind::GainCurrentBlockCardUnpoweredExact => {
            neutral::gain_current_block_card_unpowered_exact(ctx)
        }
        StepKind::GainCurrentEnergyExact => defect_uncommon::gain_current_energy_exact(ctx),
        StepKind::GangUpExact => neutral::gang_up_exact(ctx),
        StepKind::GenerateFixedShivs => shared::generate_fixed_shivs(ctx),
        StepKind::GenerateFixedStatus => shared::generate_fixed_status(ctx),
        StepKind::GenerateShivsThenInkyExact => silent_rare::generate_shivs_then_inky_exact(ctx),
        StepKind::GenerateShivsThenUpgradeExact => {
            silent_uncommon::generate_shivs_then_upgrade_exact(ctx)
        }
        StepKind::Genesis => templates::genesis(ctx),
        StepKind::GeneticAlgorithmBlockExact => defect_rare::genetic_algorithm_block_exact(ctx),
        StepKind::GeneticAlgorithmGrowthExact => defect_rare::genetic_algorithm_growth_exact(ctx),
        StepKind::GlimmerExact => single_pile_selection::glimmer_exact(ctx),
        StepKind::GlimpseBeyondExact => necrobinder_rare::glimpse_beyond_exact(ctx),
        StepKind::GoForTheEyesExact => defect_common::go_for_the_eyes_exact(ctx),
        StepKind::GuidingStarDrawNextTurnExact => {
            regent_uncommon::guiding_star_draw_next_turn_exact(ctx)
        }
        StepKind::GunkUpExact => defect_common::gunk_up_exact(ctx),
        StepKind::Hailstorm => templates::hailstorm(ctx),
        StepKind::HammerTimeExact => regent_forge::hammer_time_exact(ctx),
        StepKind::HandCapBody => hand_cap::hand_cap_body(ctx),
        StepKind::HangExact => necrobinder_rare::hang_exact(ctx),
        StepKind::HauntPower => shared::haunt_power(ctx),
        StepKind::Havoc => ironclad_common::havoc(ctx),
        StepKind::Heal => shared::heal(ctx),
        StepKind::HeavenlyDrillX => ironclad_rare::heavenly_drill_x(ctx),
        StepKind::HelixDrillExact => calculated_history::helix_drill_exact(ctx),
        StepKind::HelloWorld => templates::hello_world(ctx),
        StepKind::Hellraiser => templates::hellraiser(ctx),
        StepKind::HibernatePowerExact => defect_uncommon::hibernate_power_exact(ctx),
        StepKind::HiddenGemExact => neutral::hidden_gem_exact(ctx),
        StepKind::HpLoss => shared::hp_loss(ctx),
        StepKind::HuddleUpExact => regent_uncommon::huddle_up_exact(ctx),
        StepKind::HyperbeamFocusDownExact => defect_orb::hyperbeam_focus_down_exact(ctx),
        StepKind::IgnitionExact => defect_uncommon::ignition_exact(ctx),
        StepKind::ImitationLearningExact => defect_rare::imitation_learning_exact(ctx),
        StepKind::InfernalBladeExact => ironclad_uncommon::infernal_blade_exact(ctx),
        StepKind::Inferno => ironclad_uncommon::inferno(ctx),
        StepKind::InfiniteBlades => templates::infinite_blades(ctx),
        StepKind::Intangible => templates::intangible(ctx),
        StepKind::InterceptExact => neutral::intercept_exact(ctx),
        StepKind::Iteration => templates::iteration(ctx),
        StepKind::JackOfAllTradesExact => neutral::jack_of_all_trades_exact(ctx),
        StepKind::JackpotExact => neutral::jackpot_exact(ctx),
        StepKind::Juggernaut => templates::juggernaut(ctx),
        StepKind::JugglingExact => ironclad_uncommon::juggling_exact(ctx),
        StepKind::KnifeTrapExact => silent_rare::knife_trap_exact(ctx),
        StepKind::Knockdown => templates::knockdown(ctx),
        StepKind::LargesseExact => regent_uncommon::largesse_exact(ctx),
        StepKind::LegionOfBoneExact => necrobinder_uncommon::legion_of_bone_exact(ctx),
        StepKind::Lethality => shared::lethality(ctx),
        StepKind::LiftExact => neutral::lift_exact(ctx),
        StepKind::LightningRod => defect_orb::lightning_rod(ctx),
        StepKind::Loop => templates::loop_(ctx),
        StepKind::MachineLearning => templates::machine_learning(ctx),
        StepKind::MadScienceChaosExact => neutral::mad_science_chaos_exact(ctx),
        StepKind::MalaiseX => silent_rare::malaise_x(ctx),
        StepKind::ManifestAuthorityExact => regent_uncommon::manifest_authority_exact(ctx),
        StepKind::MasterPlanner => physical_lifecycle::master_planner(ctx),
        StepKind::MaulExact => physical_cost::maul_exact(ctx),
        StepKind::Mayhem => templates::mayhem(ctx),
        StepKind::MetamorphosisExact => neutral::metamorphosis_exact(ctx),
        StepKind::MeteorShowerExact => regent_ancient::meteor_shower_exact(ctx),
        StepKind::MimicExact => neutral::mimic_exact(ctx),
        StepKind::MirageTotalPoisonBlockExact => {
            silent_uncommon::mirage_total_poison_block_exact(ctx)
        }
        StepKind::MiseryExact => necrobinder_rare::misery_exact(ctx),
        StepKind::MoltenVuln => ironclad_common::molten_vuln(ctx),
        StepKind::MomentumStrikeExact => physical_cost::momentum_strike_exact(ctx),
        StepKind::MonarchsGaze => templates::monarchs_gaze(ctx),
        StepKind::Monologue => regent_uncommon::monologue(ctx),
        StepKind::NecroMastery => templates::necro_mastery(ctx),
        StepKind::Neurosurge => templates::neurosurge(ctx),
        StepKind::NoDraw => templates::no_draw(ctx),
        StepKind::Nostalgia => neutral::nostalgia(ctx),
        StepKind::NoxiousFumes => templates::noxious_fumes(ctx),
        StepKind::Oblivion => templates::oblivion(ctx),
        StepKind::OneForAllExact => defect_rare::one_for_all_exact(ctx),
        StepKind::OneTwoPunch => templates::one_two_punch(ctx),
        StepKind::Orbit => templates::orbit(ctx),
        StepKind::OstyBody => necrobinder_osty::osty_body(ctx),
        StepKind::OstySummonHeal => necrobinder_osty::osty_summon_heal(ctx),
        StepKind::OutbreakExact => silent_rare::outbreak_exact(ctx),
        StepKind::OutrageExact => ironclad_uncommon::outrage_exact(ctx),
        StepKind::PactsEndExact => ironclad_rare::pacts_end_exact(ctx),
        StepKind::Pagestorm => templates::pagestorm(ctx),
        StepKind::PaleBlueDot => templates::pale_blue_dot(ctx),
        StepKind::Panache => templates::panache(ctx),
        StepKind::PanicButtonExact => neutral::panic_button_exact(ctx),
        StepKind::Parry => regent_forge::parry(ctx),
        StepKind::PhantomBlades => templates::phantom_blades(ctx),
        StepKind::PhysicalDamageAttack => physical_cost::physical_damage_attack(ctx),
        StepKind::PillageExact => silent_uncommon::pillage_exact(ctx),
        StepKind::PillarOfCreation => templates::pillar_of_creation(ctx),
        StepKind::Plating => templates::plating(ctx),
        StepKind::PlotExact => regent_uncommon::plot_exact(ctx),
        StepKind::Poison => templates::poison(ctx),
        StepKind::PoisonIfPoisoned => silent_uncommon::poison_if_poisoned(ctx),
        StepKind::PoisonRandomSerial => silent_uncommon::poison_random_serial(ctx),
        StepKind::PowerAllSerial => shared::power_all_serial(ctx),
        StepKind::PrepTime => templates::prep_time(ctx),
        StepKind::PrimalForceExact => ironclad_rare::primal_force_exact(ctx),
        StepKind::PullFromBelowExact => calculated_history::pull_from_below_exact(ctx),
        StepKind::PurityExact => neutral::purity_exact(ctx),
        StepKind::Pyre => templates::pyre(ctx),
        StepKind::QuasarExact => regent_uncommon::quasar_exact(ctx),
        StepKind::RadiateExact => calculated_history::radiate_exact(ctx),
        StepKind::Rage => templates::rage(ctx),
        StepKind::RallyExact => neutral::rally_exact(ctx),
        StepKind::RampageExact => physical_cost::rampage_exact(ctx),
        StepKind::RandomOrbLoopExact => defect_uncommon::random_orb_loop_exact(ctx),
        StepKind::RattleExact => calculated_history::rattle_exact(ctx),
        StepKind::ReaperForm => templates::reaper_form(ctx),
        StepKind::RebootShuffleExact => defect_rare::reboot_shuffle_exact(ctx),
        StepKind::Rebound => neutral::rebound(ctx),
        StepKind::Reflect => templates::reflect(ctx),
        StepKind::RemoveOrbSlotsExact => defect_orb::remove_orb_slots_exact(ctx),
        StepKind::RendExact => neutral::rend_exact(ctx),
        StepKind::RestlessnessExact => neutral::restlessness_exact(ctx),
        StepKind::RetainHand => templates::retain_hand(ctx),
        StepKind::RollingBoulder => templates::rolling_boulder(ctx),
        StepKind::Rupture => templates::rupture(ctx),
        StepKind::SacrificeOstyExact => necrobinder_osty::sacrifice_osty_exact(ctx),
        StepKind::SameTurnHistoryBody => same_turn_history::same_turn_history_body(ctx),
        StepKind::ScrapeExact => defect_uncommon::scrape_exact(ctx),
        StepKind::SealedThrone => templates::sealed_throne(ctx),
        StepKind::SeekerStrikeExact => neutral::seeker_strike_exact(ctx),
        StepKind::Select => shared::select(ctx),
        StepKind::SentryMode => templates::sentry_mode(ctx),
        StepKind::SerpentForm => shared::serpent_form(ctx),
        StepKind::ShadowStepDiscardExact => silent_rare::shadow_step_discard_exact(ctx),
        StepKind::ShadowStepPowerExact => silent_rare::shadow_step_power_exact(ctx),
        StepKind::Shadowmeld => shared::shadowmeld(ctx),
        StepKind::SharedFateExact => necrobinder_rare::shared_fate_exact(ctx),
        StepKind::ShatterOrbsExact => defect_orb::shatter_orbs_exact(ctx),
        StepKind::ShivAttack => silent_special::shiv_attack(ctx),
        StepKind::ShockwaveExact => ironclad_uncommon::shockwave_exact(ctx),
        StepKind::Shroud => shared::shroud(ctx),
        StepKind::SicEmExact => necrobinder_osty::sic_em_exact(ctx),
        StepKind::SignalBoost => templates::signal_boost(ctx),
        StepKind::SleightOfFlesh => templates::sleight_of_flesh(ctx),
        StepKind::Smokestack => templates::smokestack(ctx),
        StepKind::Sneaky => templates::sneaky(ctx),
        StepKind::SoulBody => shared::soul_body(ctx),
        StepKind::SoulboundExact => necrobinder_uncommon::soulbound_exact(ctx),
        StepKind::SovereignBladeExact => regent_forge::sovereign_blade_exact(ctx),
        StepKind::SpectrumShift => shared::spectrum_shift(ctx),
        StepKind::Speedster => templates::speedster(ctx),
        StepKind::Spinner => shared::spinner(ctx),
        StepKind::SpiritOfAsh => templates::spirit_of_ash(ctx),
        StepKind::SplashExact => neutral::splash_exact(ctx),
        StepKind::Stampede => templates::stampede(ctx),
        StepKind::StarNextTurn => templates::star_next_turn(ctx),
        StepKind::Stars => shared::stars(ctx),
        StepKind::StokeExact => ironclad_rare::stoke_exact(ctx),
        StepKind::StompExact => ironclad_uncommon::stomp_exact(ctx),
        StepKind::Storm => defect_orb::storm(ctx),
        StepKind::StormOfSteelExact => silent_rare::storm_of_steel_exact(ctx),
        StepKind::Strangle => templates::strangle(ctx),
        StepKind::Stratagem => templates::stratagem(ctx),
        StepKind::Strength => shared::strength(ctx),
        StepKind::StrengthEnemy => templates::strength_enemy(ctx),
        StepKind::StunTarget => neutral::stun_target(ctx),
        StepKind::Subroutine => templates::subroutine(ctx),
        StepKind::Summon => shared::summon(ctx),
        StepKind::SummonNextTurn => templates::summon_next_turn(ctx),
        StepKind::SwordSage => regent_forge::sword_sage(ctx),
        StepKind::SynchronizeUniqueOrbFocusExact => {
            defect_orb::synchronize_unique_orb_focus_exact(ctx)
        }
        StepKind::TagTeamExact => neutral::tag_team_exact(ctx),
        StepKind::TankExact => ironclad_rare::tank_exact(ctx),
        StepKind::TearAsunderExact => calculated_history::tear_asunder_exact(ctx),
        StepKind::TempDexterity => templates::temp_dexterity(ctx),
        StepKind::TempFocus => defect_orb::temp_focus(ctx),
        StepKind::TempStrength => shared::temp_strength(ctx),
        StepKind::TempStrengthEnemy => templates::temp_strength_enemy(ctx),
        StepKind::TeslaCoil => defect_orb::tesla_coil(ctx),
        StepKind::TheBallExact => neutral::the_ball_exact(ctx),
        StepKind::TheBombExact => neutral::the_bomb_exact(ctx),
        StepKind::TheGambit => templates::the_gambit(ctx),
        StepKind::TheHuntExact => silent_rare::the_hunt_exact(ctx),
        StepKind::TheScytheExact => necrobinder_rare::the_scythe_exact(ctx),
        StepKind::Thorns => templates::thorns(ctx),
        StepKind::ThrashExact => ironclad_rare::thrash_exact(ctx),
        StepKind::Thunder => defect_orb::thunder(ctx),
        StepKind::ThunderclapExact => ironclad_common::thunderclap_exact(ctx),
        StepKind::ToolsOfTheTrade => shared::tools_of_the_trade(ctx),
        StepKind::ToricToughnessExact => neutral::toric_toughness_exact(ctx),
        StepKind::Tracking => templates::tracking(ctx),
        StepKind::TrashToTreasure => templates::trash_to_treasure(ctx),
        StepKind::TurnEndGoldLossExact => curses::turn_end_gold_loss_exact(ctx),
        StepKind::TutorExact => regent_uncommon::tutor_exact(ctx),
        StepKind::Tyranny => shared::tyranny(ctx),
        StepKind::UndeathExact => necrobinder_rare::undeath_exact(ctx),
        StepKind::Underworld => templates::underworld(ctx),
        StepKind::Unmovable => templates::unmovable(ctx),
        StepKind::UpMySleeveCostExact => silent_uncommon::up_my_sleeve_cost_exact(ctx),
        StepKind::UpgradeAllCombatExceptSourceExact => {
            neutral::upgrade_all_combat_except_source_exact(ctx)
        }
        StepKind::UpgradeAllHand => ironclad_common::upgrade_all_hand(ctx),
        StepKind::UproarExact => defect_common::uproar_exact(ctx),
        StepKind::Vicious => shared::vicious(ctx),
        StepKind::Vigor => templates::vigor(ctx),
        StepKind::VoidForm => regent_uncommon::void_form(ctx),
        StepKind::Vulnerable => shared::vulnerable(ctx),
        StepKind::VulnerableThenStrengthCurrent => {
            ironclad_uncommon::vulnerable_then_strength_current(ctx)
        }
        StepKind::Weak => shared::weak(ctx),
        StepKind::WellLaidPlans => silent_uncommon::well_laid_plans(ctx),
        StepKind::WhiteNoiseExact => defect_uncommon::white_noise_exact(ctx),
        StepKind::WraithForm => templates::wraith_form(ctx),
    }
}
