#!/usr/bin/env python3
"""Decoder for Slay the Spire 2 combat replay files (replays/latest.mcr).

SHELVED for the product (July 2026): the game keeps only latest.mcr,
overwritten every combat, so user-facing capture requires a resident
watcher app — install friction we decided against (issue #66; #61/#28
closed wontfix). In active DEV-SIDE use since #118 (2026-07-14) as the
input-log half of the live-play validation harness (tools/mcr_watch.py,
tools/mcr_validate.py). MCR_FORMAT.md "Counter caveat" is WITHDRAWN as of
#639: the snapshot's rng dict always carried every stream cumulatively —
the old "it only holds UpFront" reading was an evaluation-order bug in this
file. v0.109 additionally carries each stream's xoshiro state and a full
combat-state snapshot per action in the checksum section.

The game writes one CombatReplay per combat via a bit-packing serializer
(MegaCrit.Sts2.Core.Multiplayer.Serialization.PacketWriter): values are
written LSB-first into a little-endian bitstream. The schema below is a
direct transcription of the IL of each type's Serialize/Deserialize in
sts2.dll — v0.108.0 originally, re-derived on v0.109.1 in #639 (see
MCR_FORMAT.md and tools/dump_serializer.py). Where the two builds differ
the decoder branches on the header's version string. v0.110.1 carries the
v0.109.1 schema unchanged (#807): only the net-id tables moved.

Model ids (cards, relics, encounters, ...) are stored as compact integer
"net ids"; the lookup tables live in mcr_tables.json, generated by
tools/build_mcr_tables.py from the installed sts2.dll. The tables'
XxHash32 must match the file's modelIdHash header field — decode() checks.
Net ids are assigned per game build, so the tables are version-specific:
decode() reads the version string out of the header and picks the matching
table file (see TABLES_BY_VERSION).

Usage:
    python3 mcr_parser.py [path/to/latest.mcr] [--json out.json]
"""
import argparse
import json
import struct
from pathlib import Path

_HERE = Path(__file__).resolve().parent
TABLES_PATH = _HERE / "mcr_tables.json"

# mcr_tables.json tracks the CURRENT game version (regenerate it after every
# version bump: tools/build_mcr_tables.py). Older builds whose replays we
# still decode get a frozen copy, because their sts2.dll may be gone — Steam
# deletes old builds, and v0.108.0's is (see dll-archive/README.md), so
# mcr_tables_v0.108.0.json can never be rebuilt and must not be regenerated.
# v0.109.0 replays decode with the v0.109.1 tables: the #625 impact check
# found the two builds CIL-identical, so their net-id registries are equal.
TABLES_BY_VERSION = {
    "v0.108.0": _HERE / "mcr_tables_v0.108.0.json",
    "v0.109.0": _HERE / "mcr_tables_v0.109.1.json",
    "v0.109.1": _HERE / "mcr_tables_v0.109.1.json",
    "v0.110.1": _HERE / "mcr_tables_v0.110.1.json",
}

_TABLE_CACHE = {}


def load_tables(path):
    path = Path(path)
    if path not in _TABLE_CACHE:
        _TABLE_CACHE[path] = json.loads(path.read_text())
    return _TABLE_CACHE[path]


def tables_for_version(version):
    """The net-id tables for the game build that wrote a replay."""
    return load_tables(TABLES_BY_VERSION.get(version, TABLES_PATH))


# NetTypeCache assigns byte ids to INetAction implementations sorted by
# class name (ordinal); INetActionSubtypes lists exactly these 11.
NET_ACTION_TYPES = [
    "NetConsoleCmdGameAction",
    "NetDiscardPotionGameAction",
    "NetEndPlayerTurnAction",
    "NetMoveToMapCoordAction",
    "NetPickRelicAction",
    "NetPlayCardAction",
    "NetReadyToBeginEnemyTurnAction",
    "NetUndoEndPlayerTurnAction",
    "NetUsePotionAction",
    "NetVoteForMapCoordAction",
    "NetVoteToMoveToNextActAction",
]


class BitReader:
    """LSB-first bitstream over bytes (PacketReader semantics)."""

    def __init__(self, data: bytes):
        self.data = data
        self.pos = 0  # bit position

    def bits_left(self):
        return len(self.data) * 8 - self.pos

    def read_bits(self, n: int) -> int:
        if n > self.bits_left():
            raise EOFError(f"read past end: want {n} bits at bit {self.pos}, "
                           f"{self.bits_left()} left")
        v = 0
        p = self.pos
        for i in range(n):
            v |= ((self.data[p >> 3] >> (p & 7)) & 1) << i
            p += 1
        self.pos = p
        return v

    def u(self, bits):
        return self.read_bits(bits)

    def i(self, bits):
        """PacketReader.ReadInt: value goes through an Int32 LE roundtrip,
        so only a full 32-bit read can be negative."""
        v = self.read_bits(bits)
        if bits == 32 and v >= 1 << 31:
            v -= 1 << 32
        return v

    def i64(self, bits=64):
        v = self.read_bits(bits)
        if bits == 64 and v >= 1 << 63:
            v -= 1 << 64
        return v

    def boolean(self):
        return self.read_bits(1) == 1

    def f32(self):
        return struct.unpack("<f", self.read_bits(32).to_bytes(4, "little"))[0]

    def string(self):
        n = self.i(32)
        if n < 0 or n > self.bits_left() // 8:
            raise ValueError(f"bad string length {n} at bit {self.pos}")
        b = bytes(self.read_bits(8) for _ in range(n))
        return b.decode("utf-8")


class McrError(ValueError):
    pass


def parse_version(version):
    """'v0.109.1' -> (0, 109, 1); unparseable -> ()."""
    parts = version.lstrip("v").split(".")
    try:
        return tuple(int(p) for p in parts)
    except ValueError:
        return ()


class McrDecoder:
    def __init__(self, data: bytes, tables: dict | None = None):
        self.r = BitReader(data)
        # The header's first field is the game version that wrote the file.
        # Net ids AND parts of the schema are per build, so read it up front.
        self.version = BitReader(data).string()
        if tables is None:
            tables = tables_for_version(self.version)
        self.t = tables
        # Schema branches need an ordered version. Fall back to the version
        # the tables were built for (they only load if the header hash
        # matches, so that build IS this file's build), then refuse: guessing
        # a schema is worse than not decoding (I5).
        self.v = parse_version(self.version) or \
            parse_version(str(tables.get("game_version", "")))
        if not self.v:
            raise McrError(
                f"cannot order the game version {self.version!r} (tables say "
                f"{tables.get('game_version', '?')!r}), so the schema branch "
                f"is unknown")
        self.entry_bits = tables["entry_bits"]
        self.category_bits = tables["category_bits"]
        self.epoch_bits = tables["epoch_bits"]
        self.property_bits = tables["property_bits"]
        self._enum_names = {
            name: {int(k): v for k, v in spec["values"].items()}
            for name, spec in tables["enums"].items()
        }
        self._enum_bits = {name: spec["bits"]
                           for name, spec in tables["enums"].items()}

    # --- primitives -----------------------------------------------------
    def enum(self, name):
        v = self.r.i(self._enum_bits[name])
        return self._enum_names[name].get(v, f"{name}?{v}")

    def model_entry(self):
        return self.t["entries"][self.r.i(self.entry_bits)]

    def full_model_id(self):
        cat = self.t["categories"][self.r.i(self.category_bits)]
        ent = self.t["entries"][self.r.i(self.entry_bits)]
        return f"{cat}.{ent}"

    def epoch_id(self):
        return self.t["epochs"][self.r.i(self.epoch_bits)]

    def property_name(self):
        return self.t["property_names"][self.r.i(self.property_bits)]

    def model_entry_list(self):
        return [self.model_entry() for _ in range(self.r.i(32))]

    def full_model_id_list(self):
        return [self.full_model_id() for _ in range(self.r.i(32))]

    def list_of(self, fn, bits=32):
        n = self.r.i(bits)
        if n < 0 or n > 1_000_000:
            raise McrError(f"implausible list count {n} at bit {self.r.pos}")
        return [fn() for _ in range(n)]

    # --- top level --------------------------------------------------------
    def combat_replay(self):
        r = self.r
        out = {
            "version": r.string(),
            "git_commit": r.string(),
            "model_id_hash": r.u(32),
        }
        if out["model_id_hash"] != self.t["model_id_hash"]:
            raise McrError(
                f"modelIdHash mismatch: file was written by "
                f"{out['version']} ({out['git_commit']}) with "
                f"0x{out['model_id_hash']:08x}, tables are for "
                f"{self.t.get('game_version', '?')} "
                f"({self.t.get('game_commit', '?')}) with "
                f"0x{self.t['model_id_hash']:08x} — regenerate "
                f"mcr_tables.json against the matching sts2.dll "
                f"(tools/build_mcr_tables.py)")
        out["choice_ids"] = [r.u(32) for _ in range(r.i(32))]
        out["reward_ids"] = [r.i(32) for _ in range(r.i(32))]
        out["next_action_id"] = r.u(32)
        out["next_checksum_id"] = r.u(32)
        out["next_hook_id"] = r.u(32)
        out["run"] = self.serializable_run()
        out["events"] = self.list_of(self.replay_event)
        out["checksums"] = self.list_of(self.checksum_data)
        # writer pads the final byte with zero bits
        left = r.bits_left()
        if left >= 8 or (left and r.read_bits(left) != 0):
            raise McrError(f"{left} unconsumed bits after decode")
        return out

    # --- run snapshot -----------------------------------------------------
    def serializable_run(self):
        r = self.r
        out = {"schema_version": r.i(32)}
        out["acts"] = self.list_of(self.act_model)
        out["modifiers"] = self.list_of(self.modifier)
        out["daily_time"] = r.i64() if r.boolean() else None
        out["game_mode"] = self.enum("GameMode")
        out["current_act_index"] = r.i(4)
        out["events_seen"] = self.model_entry_list()
        out["pre_finished_room"] = self.room() if r.boolean() else None
        out["run_odds"] = {
            "card_reward_odds": r.f32(),
            "potion_reward_odds": r.f32(),
            "relic_reward_odds": r.f32(),
            "gold_reward_odds": r.f32(),
        }
        out["players"] = self.list_of(self.player)
        out["rng"] = self.run_rng_set()
        out["shared_relic_grab_bag"] = self.relic_grab_bag()
        out["visited_map_coords"] = self.list_of(self.map_coord)
        out["map_point_history"] = self.list_of(
            lambda: self.list_of(self.map_point_history_entry))
        out["save_time"] = r.i64()
        out["start_time"] = r.i64()
        out["run_time"] = r.i64()
        out["win_time"] = r.i64()
        out["ascension"] = r.i(8)
        out["map_drawings"] = self.map_drawings() if r.boolean() else None
        out["extra_fields"] = {
            "started_with_neow": r.boolean(),
            "test_subject_kills": r.i(32),
            "freed_repy": r.boolean(),
        }
        out["num_reloads"] = r.i(32)
        return out

    def act_model(self):
        r = self.r
        return {
            "id": self.model_entry(),
            "rooms": self.room_set(),
            "saved_map": self.act_map() if r.boolean() else None,
        }

    def modifier(self):
        return {
            "id": self.model_entry(),
            "props": self.saved_properties() if self.r.boolean() else None,
        }

    def room_set(self):
        r = self.r
        out = {
            "event_ids": self.model_entry_list(),
            "events_visited": r.i(32),
            "normal_encounter_ids": self.model_entry_list(),
            "normal_encounters_visited": r.i(32),
            "elite_encounter_ids": self.model_entry_list(),
            "elites_visited": r.i(32),
            "bosses_visited": r.i(32),
        }
        out["boss_id"] = self.model_entry() if r.boolean() else None
        out["second_boss_id"] = self.model_entry() if r.boolean() else None
        out["ancient_id"] = self.model_entry() if r.boolean() else None
        return out

    def act_map(self):
        r = self.r
        out = {"grid_width": r.i(8), "grid_height": r.i(8)}
        out["boss_point"] = self.map_point()
        out["starting_point"] = self.map_point()
        out["second_boss_point"] = self.map_point() if r.boolean() else None
        out["points"] = self.list_of(self.map_point, bits=16)
        n = r.i(8)
        out["start_map_point_coords"] = [self.map_coord() for _ in range(n)]
        return out

    def map_point(self):
        # SerializableMapPoint::Serialize (v0.111.0 RVA 0x40d80) writes Coord
        # first (Write<MapCoord>, IL_0013), THEN PointType as an 8-bit int
        # (IL_0020); Deserialize (RVA 0x40e1c) reads them in that order
        # (IL_000e, IL_001b). Reading PointType first misaligned every point:
        # `point_type` held Coord.col and `coord` held [row, PointType] (#2988).
        r = self.r
        coord = self.map_coord()
        pt = r.i(8)  # MapPointType written as a plain int8 here
        pt_name = self._enum_names["MapPointType"].get(pt, pt)
        out = {"coord": coord, "point_type": pt_name}
        out["can_be_modified"] = r.boolean()
        n = r.i(8)
        out["child_coords"] = [self.map_coord() for _ in range(n)]
        return out

    def map_coord(self):
        return [self.r.u(8), self.r.u(8)]  # col, row

    def room(self):
        r = self.r
        out = {"room_type": r.i(32)}
        out["encounter_id"] = self.model_entry() if r.boolean() else None
        out["event_id"] = self.model_entry() if r.boolean() else None
        out["gold_proportion"] = r.f32()
        out["is_pre_finished"] = r.boolean()
        out["extra_rewards"] = {
            str(r.u(64)): self.list_of(self.reward)
            for _ in range(r.i(32))
        }
        out["parent_event_id"] = self.model_entry() if r.boolean() else None
        out["should_resume_parent_event"] = r.boolean()
        out["encounter_state"] = {
            r.string(): r.string() for _ in range(r.i(32))
        }
        return out

    def reward(self):
        r = self.r
        out = {"reward_type": r.i(32),
               "predetermined_model_id": self.full_model_id()}
        if out["reward_type"] == 6:  # special card reward embeds the card
            out["special_card"] = self.card()
        out["gold_amount"] = r.i(32)
        out["was_gold_stolen_back"] = r.boolean()
        out["source"] = self.enum("CardCreationSource")
        out["rarity_odds"] = self.enum("CardRarityOddsType")
        out["card_pool_ids"] = self.model_entry_list()
        out["option_count"] = r.i(32)
        out["custom_description_encounter_source_id"] = self.model_entry()
        return out

    def player(self):
        r = self.r
        out = {
            "net_id": r.u(64),
            "character": self.model_entry(),
            "current_hp": r.i(32),
            "max_hp": r.i(32),
            "max_energy": r.i(16),
            "max_potion_slots": r.i(8),
            "gold": r.i(32),
            "base_orb_slots": r.i(16),
            "deck": self.list_of(self.card),
            "relics": self.list_of(self.relic),
            "potions": self.list_of(self.potion),
            "player_rng": self.player_rng_set(),
            "odds": {"card_rarity_odds_value": r.f32(),
                     "potion_reward_odds_value": r.f32()},
            "relic_grab_bag": self.relic_grab_bag(),
            "extra_fields": {
                "card_shop_removals_used": r.i(32),
                "wongo_points": r.i(32),
                "cccombo_badge_unlocked": r.boolean(),
                "damage_dealt": r.i(32),
                "debuffs_applied": r.i(32),
            },
            "unlock_state": {
                "unlocked_epochs": [self.epoch_id()
                                    for _ in range(r.i(32))],
                "encounters_seen": self.model_entry_list(),
                "number_of_runs": r.i(16),
            },
            "discovered_cards": self.full_model_id_list(),
            "discovered_enemies": self.full_model_id_list(),
            "discovered_epochs": [self.epoch_id() for _ in range(r.i(32))],
            "discovered_potions": self.full_model_id_list(),
            "discovered_relics": self.full_model_id_list(),
        }
        return out

    def card(self):
        r = self.r
        out = {"id": self.model_entry(), "upgrade_level": r.i(8)}
        out["enchantment"] = self.enchantment() if r.boolean() else None
        out["props"] = self.saved_properties() if r.boolean() else None
        out["floor_added_to_deck"] = r.i(8) if r.boolean() else None
        return out

    def enchantment(self):
        r = self.r
        out = {"id": self.model_entry(), "level": r.i(8)}
        out["props"] = self.saved_properties() if r.boolean() else None
        return out

    def relic(self):
        r = self.r
        out = {"id": self.model_entry()}
        out["props"] = self.saved_properties() if r.boolean() else None
        out["floor_added"] = r.i(8) if r.boolean() else None
        return out

    def potion(self):
        return {"id": self.model_entry(), "slot": self.r.i(4)}

    def rng(self):
        """One rng stream.

        v0.108 stored just the counter. v0.109 replaced it with
        SerializableRng = counter (int32) + the four xoshiro256** state
        words (uint64 each) — RVA 0x408fc.
        """
        r = self.r
        if self.v < (0, 109):
            return r.i(32), None
        return r.i(32), [r.u(64) for _ in range(4)]

    def rng_set(self, enum_name, seed_reader):
        seed = seed_reader()
        counters, states = {}, {}
        for _ in range(self.r.i(8)):
            name = self.enum(enum_name)
            counters[name], state = self.rng()
            if state is not None:
                states[name] = state
        out = {"seed": seed, "counters": counters}
        if states:
            out["states"] = states
        return out

    def run_rng_set(self):
        return self.rng_set("RunRngType", self.r.string)

    def player_rng_set(self):
        # v0.108 wrote the player seed as a uint32; v0.109 widened it to the
        # uint64 the field always was (SerializablePlayerRngSet, RVA 0x4042c).
        bits = 32 if self.v < (0, 109) else 64
        return self.rng_set("PlayerRngType", lambda: self.r.u(bits))

    def relic_grab_bag(self):
        out = {}
        for _ in range(self.r.i(32)):
            rarity = self.enum("RelicRarity")
            out[rarity] = self.model_entry_list()
        return out

    def saved_properties(self):
        # SavedProperties.Serialize writes WritePropertyName BEFORE the value
        # for every group. Bind the name to its own local first: in
        # `out[self.property_name()] = <value>` Python evaluates the value
        # expression first, which swaps the two reads. The bit total is the
        # same either way, so the stream stays aligned and the mistake is
        # invisible except as names paired with the wrong values.
        r = self.r
        out = {}
        if r.boolean():  # ints
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = r.i(32)
        if r.boolean():  # int arrays
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = [r.i(32) for _ in range(r.i(32))]
        if r.boolean():  # bools
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = r.boolean()
        if r.boolean():  # model ids
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = self.full_model_id()
        if r.boolean():  # cards
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = self.card()
        if r.boolean():  # card arrays
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = [self.card() for _ in range(r.i(32))]
        if r.boolean():  # strings
            for _ in range(r.i(8)):
                name = self.property_name()
                out[name] = r.string()
        return out

    # --- map history --------------------------------------------------
    def map_point_history_entry(self):
        return {
            "map_point_type": self.enum("MapPointType"),
            "rooms": self.list_of(self.map_point_room_history),
            "players": self.list_of(self.player_map_point_history),
        }

    def map_point_room_history(self):
        r = self.r
        out = {"room_type": self.enum("RoomType")}
        out["model_id"] = self.full_model_id() if r.boolean() else None
        out["monster_ids"] = self.model_entry_list()
        out["turns_taken"] = r.i(32)
        return out

    def player_map_point_history(self):
        r = self.r
        return {
            "player_id": r.u(64),
            "gold_gained": r.i(32),
            "gold_spent": r.i(32),
            "gold_lost": r.i(32),
            "gold_stolen": r.i(32),
            "stolen_loot": r.i(32),
            "current_gold": r.i(32),
            "current_hp": r.i(32),
            "max_hp": r.i(32),
            "damage_taken": r.i(32),
            "hp_healed": r.i(32),
            "max_hp_gained": r.i(32),
            "max_hp_lost": r.i(32),
            "event_choices": self.list_of(self.event_option_history),
            "ancient_choices": self.list_of(self.ancient_choice_history),
            "cards_gained": self.list_of(self.card),
            "card_choices": self.list_of(self.card_choice_history),
            "relic_choices": self.list_of(self.model_choice_history),
            "potion_choices": self.list_of(self.model_choice_history),
            "potions_discarded": self.model_entry_list(),
            "potions_used": self.model_entry_list(),
            "cards_removed": self.list_of(self.card),
            "relics_removed": self.model_entry_list(),
            "cards_enchanted": self.list_of(self.card_enchantment_history),
            "cards_transformed": self.list_of(
                self.card_transformation_history),
            "cards_upgraded": self.model_entry_list(),
            "cards_downgraded": self.model_entry_list(),
            "event_choices_2": self.list_of(self.event_option_history),
            "rest_site_choices": [r.string() for _ in range(r.i(32))],
            "bought_relics": self.model_entry_list(),
            "bought_potions": self.model_entry_list(),
            "bought_colorless": self.model_entry_list(),
            "completed_quests": self.model_entry_list(),
            "is_affected_by_fur_coat": r.boolean(),
        }

    def event_option_history(self):
        r = self.r
        out = {"title_loc_table": r.string(), "title_loc_key": r.string()}
        if r.boolean():
            out["variables"] = {}
            for _ in range(r.i(32)):
                key = r.string()
                out["variables"][key] = self.dynamic_var()
        return out

    def dynamic_var(self):
        t = self.enum("DynamicVarType")
        r = self.r
        # SerializableDynamicVar.Serialize switch on 1-based type:
        # 1 BaseDynamic, 3 Decimal -> float32 (decimalValue, unquantized);
        # 2 DynamicString, 4 String -> string; 5 Bool -> bool.
        # (The first .mcr sample had zero variables anywhere, so the
        # original transcription had the float/string branches swapped
        # and it went unnoticed until a live SUNKEN_STATUE choice.)
        idx = {v: int(k) for k, v in
               self.t["enums"]["DynamicVarType"]["values"].items()}[t]
        if idx in (1, 3):
            return r.f32()
        if idx in (2, 4):
            return r.string()
        if idx == 5:
            return r.boolean()
        raise McrError(f"bad DynamicVarType {t}")

    def ancient_choice_history(self):
        r = self.r
        return {"a": r.string(), "b": r.string(), "flag": r.boolean()}

    def card_choice_history(self):
        return {"card": self.card(), "picked": self.r.boolean()}

    def model_choice_history(self):
        return {"id": self.model_entry(), "picked": self.r.boolean()}

    def card_enchantment_history(self):
        return {"card": self.card(), "enchantment_id": self.model_entry()}

    def card_transformation_history(self):
        return {"from": self.card(), "to": self.card()}

    def map_drawings(self):
        return self.list_of(self.player_map_drawings)

    def player_map_drawings(self):
        r = self.r
        return {"player_id": r.u(64),
                "lines": self.list_of(self.map_drawing_line)}

    def map_drawing_line(self):
        # SerializableMapDrawingLine: bool + count(16) + points
        raise McrError("map drawing decode not implemented "
                       "(no sample file exercises it)")

    # --- events ---------------------------------------------------------
    def replay_event(self):
        r = self.r
        etype = r.i(3)
        name = {1: "GameAction", 2: "HookAction",
                3: "ResumeAction", 4: "PlayerChoice"}.get(etype)
        out = {"event_type": name or f"?{etype}"}
        if etype == 1:  # GameAction
            out["player_id"] = r.u(64)
            action_id = r.u(8)
            out["action"] = self.net_action(action_id)
        elif etype == 2:  # HookAction
            out["player_id"] = r.u(64)
            out["hook_id"] = r.u(32)
            out["game_action_type"] = self.enum("GameActionType")
        elif etype == 3:  # ResumeAction
            out["action_id"] = r.u(32)
        elif etype == 4:  # PlayerChoice
            out["player_id"] = r.u(64)
            out["choice_id"] = r.u(32)
            out["result"] = self.player_choice_result()
        else:
            raise McrError(f"bad CombatReplayEventType {etype}")
        return out

    def net_action(self, action_id):
        r = self.r
        try:
            name = NET_ACTION_TYPES[action_id]
        except IndexError:
            raise McrError(f"unknown net action id {action_id}")
        out = {"type": name}
        if name == "NetConsoleCmdGameAction":
            out["cmd"] = r.string()
            out["in_combat"] = r.boolean()
        elif name == "NetDiscardPotionGameAction":
            out["potion_slot_index"] = r.u(4)
            out["was_enqueued_in_combat"] = r.boolean()
        elif name in ("NetEndPlayerTurnAction", "NetUndoEndPlayerTurnAction"):
            out["turn_number"] = r.i(16)
        elif name == "NetMoveToMapCoordAction":
            out["destination"] = self.map_coord()
        elif name == "NetPickRelicAction":
            out["relic_index"] = r.i(8) if r.boolean() else None
        elif name == "NetPlayCardAction":
            out["combat_card_index"] = r.u(16)
            out["card_id"] = self.model_entry()
            out["target_id"] = r.u(6) if r.boolean() else None
        elif name == "NetReadyToBeginEnemyTurnAction":
            pass
        elif name == "NetUsePotionAction":
            out["potion_index"] = r.u(4)
            out["enqueued_in_combat"] = r.boolean()
            out["target_id"] = r.u(6) if r.boolean() else None
            out["target_player_id"] = r.u(64) if r.boolean() else None
        elif name == "NetVoteForMapCoordAction":
            out["source"] = {"act_index": r.i(4),
                             "coord": self.map_coord()
                             if r.boolean() else None}
            out["destination"] = ({"map_generation_count": r.i(4),
                                   "coord": self.map_coord()}
                                  if r.boolean() else None)
        elif name == "NetVoteToMoveToNextActAction":
            out["current_act_index"] = r.i(32)
        return out

    def player_choice_result(self):
        r = self.r
        ctype = self.enum("PlayerChoiceType")
        out = {"type": ctype}
        if ctype == "CanonicalCard":
            out["cards"] = [self.model_entry() for _ in range(r.i(32))]
        elif ctype == "CombatCard":
            out["combat_card_indexes"] = self.list_of(lambda: r.u(16))
        elif ctype == "DeckCard":
            out["deck_indexes"] = self.list_of(lambda: r.u(16))
        elif ctype == "MutableCard":
            out["cards"] = self.list_of(self.card)
            out["owner"] = r.u(64) if r.boolean() else None
        elif ctype == "Player":
            out["player_id"] = r.u(64) if r.boolean() else None
        elif ctype == "Index":
            out["indexes"] = [r.i(32) for _ in range(r.i(32))]
        else:
            raise McrError(f"bad PlayerChoiceType {ctype}")
        return out

    # --- checksums -------------------------------------------------------
    def checksum_data(self):
        r = self.r
        return {
            "checksum": {"id": r.u(32), "value": r.u(32)},
            "context": r.string(),
            "full_state": self.net_full_combat_state(),
        }

    def net_full_combat_state(self):
        r = self.r
        out = {"creatures": self.list_of(self.creature_state),
               "players": self.list_of(self.combat_player_state),
               "rng": self.run_rng_set(),
               "next_choice_ids": [r.u(32) for _ in range(r.i(32))],
               "next_reward_ids": [r.i(32) for _ in range(r.i(32))]}
        out["last_executed_action_id"] = r.u(32) if r.boolean() else None
        out["last_executed_hook_id"] = r.u(32) if r.boolean() else None
        return out

    # CreatureState / PlayerState & friends are nested in
    # MegaCrit.Sts2.Core.Entities.Multiplayer (RVAs are v0.109.1). v0.108
    # replays never carried a checksum, so these first became reachable with
    # the v0.109 captures — see MCR_FORMAT.md "Checksum section".
    def creature_state(self):
        # CreatureState.Serialize, RVA 0x42282c
        r = self.r
        out = {"monster_id": self.model_entry() if r.boolean() else None,
               "player_id": r.u(64) if r.boolean() else None,
               "current_hp": r.i(32),
               "max_hp": r.i(32),
               "block": r.i(32),
               "powers": self.list_of(self.power_state)}
        return out

    def power_state(self):
        # PowerState.Serialize, RVA 0x422991
        return {"id": self.model_entry(), "amount": self.r.i(32)}

    def combat_player_state(self):
        # PlayerState.Serialize, RVA 0x422a68
        r = self.r
        return {
            "player_id": r.u(64),
            "character": self.model_entry(),
            "turn_number": r.i(32),
            "phase": self.enum("PlayerTurnPhase"),
            "energy": r.i(32),
            "stars": r.i(32),
            "max_potion_count": r.i(32),
            "gold": r.i(32),
            "piles": self.list_of(self.combat_pile_state),
            # PotionState is a bare model entry; RelicState is one
            # SerializableRelic (RVAs 0x422f3c / 0x422f58)
            "potions": self.list_of(self.model_entry),
            "relics": self.list_of(self.relic),
            "orbs": self.list_of(self.orb_state),
            "player_rng": self.player_rng_set(),
            "relic_grab_bag": self.relic_grab_bag(),
        }

    def orb_state(self):
        # OrbState.Serialize, RVA 0x4229c9
        r = self.r
        return {"id": self.model_entry(), "passive": r.i(16),
                "evoke": r.i(16)}

    def combat_pile_state(self):
        # CombatPileState.Serialize, RVA 0x422c27 — pileType is written as a
        # raw int32, not through WriteEnum.
        pile = self.r.i(32)
        table = self.t["enums"].get("PileType")
        if table is None:
            raise McrError(
                "tables have no PileType enum, so a combat-state pile cannot "
                "be labelled — rebuild them with tools/build_mcr_tables.py")
        return {"pile_type": table["values"].get(str(pile),
                                                 f"PileType?{pile}"),
                "cards": self.list_of(self.card_state)}

    def card_state(self):
        # CardState.Serialize, RVA 0x422ce0
        r = self.r
        out = {"card": self.card()}
        if r.boolean():
            out["affliction"] = self.model_entry()
            out["affliction_count"] = r.i(32)
        else:
            out["affliction"] = None
        out["energy_cost"] = r.i(32) if r.boolean() else None
        # keyword count is 3 bits wide
        out["keywords"] = ([self.enum("CardKeyword") for _ in range(r.i(3))]
                           if r.boolean() else None)
        return out


def decode(path, tables=None):
    return McrDecoder(Path(path).read_bytes(), tables).combat_replay()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mcr", nargs="?", default=str(
        Path(__file__).resolve().parent / "testdata" / "latest.mcr"))
    ap.add_argument("--json", help="write full decode to this path")
    args = ap.parse_args()

    replay = decode(args.mcr)
    if args.json:
        Path(args.json).write_text(json.dumps(replay, indent=1))

    run = replay["run"]
    p = run["players"][0]
    print(f"version {replay['version']} commit {replay['git_commit']} "
          f"(modelIdHash ok)")
    print(f"seed {run['rng']['seed']}  mode {run['game_mode']}  "
          f"asc {run['ascension']}  act idx {run['current_act_index']}")
    print(f"player: {p['character']}  hp {p['current_hp']}/{p['max_hp']}  "
          f"gold {p['gold']}  deck {len(p['deck'])} cards")
    print("rng counters at combat start:")
    for k, v in run["rng"]["counters"].items():
        print(f"  {k:24s} {v}")
    print(f"{len(replay['events'])} events, "
          f"{len(replay['checksums'])} checksums")
    for e in replay["events"]:
        bits = {k: v for k, v in e.items() if k != "event_type"}
        print(f"  {e['event_type']:12s} {bits}")


if __name__ == "__main__":
    main()
