"""
Tests for the STS2 RNG port (sts2_rng.py).

Two validation layers:
1. test_vectors.json — generated by an INDEPENDENT C implementation of the
   canonical xoshiro256**/splitmix64 reference code plus the .NET
   deterministic string hash (scratch source: xoshiro_ref.c). Catches
   transcription errors in the Python port.
2. Self-consistency checks of the Rng wrapper semantics recovered from the
   IL (counter behavior, fast-forward equivalence, shuffle draw count).

NOT yet validated against the actual game (handoff tasks 3 & 5): we still
need ground-truth values logged from a live run (in-game determinism
spot-check / opening-hand replication). These tests prove the port matches
the ALGORITHM read from the IL, not that the IL was read correctly.

Run: python3 -m pytest sim/v0.111.0/python/test_sts2_rng.py  (or python3 sim/v0.111.0/python/test_sts2_rng.py)
"""

import json
import pathlib
import sys
import pytest

sys.path.insert(0, str(pathlib.Path(__file__).parent))

from sts2_rng import (  # noqa: E402
    GAME_BUILD_V0_111_0, MegaRandom, PlayerRngSet, Rng, RunRngSet,
    RUN_RNG_STREAMS,
    deterministic_hash_code, snake_case,
)

VECTORS = json.loads(
    (pathlib.Path(__file__).parent / "test_vectors.json").read_text())
V109_MIDRUN_PIN = json.loads((
    pathlib.Path(__file__).parent / "testdata/v0109_rng_midrun_pin.json"
).read_text())


def test_splitmix64_seeding_matches_reference():
    for seed_str, v in VECTORS["seeds"].items():
        m = MegaRandom(int(seed_str))
        assert [m.s0, m.s1, m.s2, m.s3] == v["state"], f"seed {seed_str}"


def test_xoshiro_next_matches_reference():
    for seed_str, v in VECTORS["seeds"].items():
        m = MegaRandom(int(seed_str))
        assert [m.next_ulong() for _ in range(12)] == v["next"]


def test_next_double_matches_reference():
    for seed_str, v in VECTORS["seeds"].items():
        m = MegaRandom(int(seed_str))
        for expected in v["doubles"]:
            assert m.next_double() == expected


def test_next_max_matches_reference():
    for seed_str, v in VECTORS["seeds"].items():
        m = MegaRandom(int(seed_str))
        assert [m.next(100) for _ in range(12)] == v["next100"]


def test_deterministic_hash_matches_reference():
    for s, expected in VECTORS["hashes"].items():
        assert deterministic_hash_code(s) == expected, repr(s)


def test_snake_case():
    assert snake_case("UpFront") == "up_front"
    assert snake_case("CombatCardGeneration") == "combat_card_generation"
    assert snake_case("UnknownMapPoint") == "unknown_map_point"
    assert snake_case("MonsterAi") == "monster_ai"
    assert snake_case("Niche") == "niche"
    assert snake_case("Shuffle") == "shuffle"
    assert snake_case("CombatOrbs") == "combat_orbs"
    assert snake_case("TreasureRoomRelics") == "treasure_room_relics"
    assert snake_case("Transformations") == "transformations"


def test_negative_seed_zero_extends():
    # Rng passes its int32 seed through CIL conv.u8 (zero-extension):
    # seed -1 must behave like 0xFFFFFFFF, not 0xFFFFFFFFFFFFFFFF.
    assert Rng(-1)._random.next_ulong() == \
        MegaRandom(0xFFFFFFFF).next_ulong()


def test_counter_and_fast_forward_equivalence():
    # A fresh Rng fast-forwarded to counter N must produce the same draws
    # as an Rng that made N calls (any mix of draw methods).
    a = Rng(123456)
    a.next_int(100)
    a.next_bool()
    a.next_double()
    a.next_float(1.0)
    a.next_unsigned_int(5, 50)
    assert a.counter == 5

    b = Rng(123456, counter=5)
    assert b.counter == 5
    assert [a.next_int(1000) for _ in range(8)] == \
        [b.next_int(1000) for _ in range(8)]


def test_shuffle_semantics():
    # n-1 counter ticks; exact permutation pinned against a manual
    # replay of the IL algorithm (top-down Fisher-Yates, j = next_int(i+1)).
    rng = Rng(42)
    items = list(range(10))
    rng.shuffle(items)
    assert rng.counter == 9

    replay = Rng(42)
    manual = list(range(10))
    for i in range(9, 0, -1):
        j = replay.next_int(i + 1)
        manual[j], manual[i] = manual[i], manual[j]
    assert items == manual
    assert sorted(items) == list(range(10))


def test_stream_seed_derivation():
    # run stream seed = hash(seed_string) + hash(snake_case(name)), int32 wrap
    seed_string = "ZPJHU3WSH2"
    rs = RunRngSet(seed_string)
    assert rs.seed == deterministic_hash_code(seed_string) == 1584024330
    for name in RUN_RNG_STREAMS:
        expected = rs.seed + deterministic_hash_code(snake_case(name))
        expected = ((expected & 0xFFFFFFFF) ^ 0x80000000) - 0x80000000
        assert rs[name].seed == expected, name

    # player set: + slot index before per-stream hash
    p0 = PlayerRngSet(seed_string, 0)
    p1 = PlayerRngSet(seed_string, 1)
    assert p1.seed == p0.seed + 1
    assert p0["Rewards"].seed != p1["Rewards"].seed


def test_streams_are_independent():
    rs = RunRngSet("ZPJHU3WSH2")
    shuffle_draws = [rs["Shuffle"].next_int(1000) for _ in range(5)]
    rs2 = RunRngSet("ZPJHU3WSH2")
    _ = [rs2["MonsterAi"].next_int(1000) for _ in range(50)]
    assert [rs2["Shuffle"].next_int(1000) for _ in range(5)] == shuffle_draws


def test_fight1_shuffle_matches_live_game_ground_truth():
    """END-TO-END GAME VALIDATION (2026-07-08): Sean replayed seed
    ZPJHU3WSH2 (Ironclad A10, build v0.108.0) and recorded the first
    fight's draws, turns 1-3. Model: save-file deck order, one Shuffle-
    stream Fisher-Yates at counter 0, drawn from the front. The full
    11-card permutation matched; sole hit in a 2880-hypothesis space."""
    from predict_opening_hand import predict
    assert predict("ZPJHU3WSH2") == [
        "Strike", "Defend", "Strike", "Bash", "Defend",          # turn 1
        "Defend", "Strike", "AscendersBane", "Strike", "Defend",  # turn 2
        "Strike",                                                 # turn 3
    ]


def test_out_of_sample_seed_prediction_confirmed_in_game():
    """OUT-OF-SAMPLE VALIDATION (2026-07-08): we PREDICTED these hands for
    custom seed CLAUDE before it was ever played; Sean then played it
    (Ironclad A10, build v0.108.0) and confirmed both turns card-for-card.
    Rules out coincidental-match concerns from the hypothesis search."""
    from predict_opening_hand import predict
    assert predict("CLAUDE")[:10] == [
        "Defend", "AscendersBane", "Bash", "Defend", "Strike",   # turn 1
        "Strike", "Strike", "Defend", "Defend", "Strike",        # turn 2
    ]


def test_replay_fight_counter_accounting():
    """Fight-N replay (issue #60): fight 0 must reproduce the confirmed
    ground truth through replay_fight's code path, and the Shuffle counter
    entering fight 1 must be 27 for the recorded 5-turn fight 0
    (10 initial + 8 turn-3 reshuffle [Bane exhausted] + 9 turn-5 reshuffle).
    In-game verification of the fight-1 prediction is pending."""
    import json
    import pathlib
    from replay_fight import fight_consumption, predict
    from sts2_rng import Rng, RunRngSet

    ids = ["CARD.STRIKE_IRONCLAD"] * 5 + ["CARD.DEFEND_IRONCLAD"] * 4 + \
          ["CARD.BASH", "CARD.ASCENDERS_BANE"]
    rng = Rng(RunRngSet("ZPJHU3WSH2")["Shuffle"].seed)
    consumed, _ = fight_consumption(ids, turns=5, rng=rng)
    assert consumed == 27

    # fight 0 opening hand via the replay path == live ground truth
    run = {
        "seed": "ZPJHU3WSH2",
        "players": [{"deck": [
            {"id": i, "floor_added_to_deck": 1} for i in ids]}],
        "map_point_history": [[
            {"map_point_type": "ancient", "player_stats": [{}]},
            {"map_point_type": "monster", "player_stats": [{}],
             "rooms": [{"model_id": "ENCOUNTER.TOADPOLES_WEAK",
                        "turns_taken": 5}]},
        ]],
    }
    tmp = pathlib.Path(__file__).parent / ".test_run_tmp.json"
    tmp.write_text(json.dumps(run))
    try:
        r = predict(str(tmp), 0)
    finally:
        tmp.unlink()
    assert r["predicted_turn1_hand"] == [
        "STRIKE_IRONCLAD", "DEFEND_IRONCLAD", "STRIKE_IRONCLAD",
        "BASH", "DEFEND_IRONCLAD"]
    assert r["shuffle_counter_entering"] == 0


def test_fight2_cross_fight_replay_confirmed_in_game():
    """CROSS-FIGHT VALIDATION (2026-07-08): Sean replayed ZPJHU3WSH2,
    finished fight 1 in 3 turns, picked Blood Wall, and recorded fight 2's
    first two hands — both matched this prediction card-for-card. Validates
    Shuffle-counter accounting across a fight (10 initial + 8 turn-3
    reshuffle after Bane exhaust = 18) and acquisition-ordered entry decks."""
    from replay_fight import fight_consumption
    from sts2_rng import Rng, RunRngSet

    starter = ["CARD.STRIKE_IRONCLAD"] * 5 + ["CARD.DEFEND_IRONCLAD"] * 4 + \
              ["CARD.BASH", "CARD.ASCENDERS_BANE"]
    rng = Rng(RunRngSet("ZPJHU3WSH2")["Shuffle"].seed)
    consumed, _ = fight_consumption(starter, turns=3, rng=rng)
    assert consumed == 18 == rng.counter

    fight2_deck = starter + ["CARD.BLOOD_WALL"]
    order = list(fight2_deck)
    rng.shuffle(order)
    short = [c.replace("CARD.", "").replace("_IRONCLAD", "") for c in order]
    assert short[:5] == ["STRIKE", "STRIKE", "ASCENDERS_BANE",
                         "DEFEND", "STRIKE"]          # observed turn 1
    assert short[5:10] == ["DEFEND", "DEFEND", "STRIKE",
                           "STRIKE", "BLOOD_WALL"]    # observed turn 2


def test_monster_intents_confirmed_in_game():
    """INTENT VALIDATION (2026-07-09): Sean confirmed from repeated A10
    Toadpole fights: front toad buffs turn 1 (gaining spikes 2), then
    attacks 4x3 on turn 2; back toad opens attacking; Seapunk rotates
    kick / spinning kick / bubble burp. Matches the IL state machines
    (deterministic — zero MonsterAi draws)."""
    from monster_ai import (predict_intents, seapunk_machine,
                            toadpole_machine)
    front = predict_intents(lambda: toadpole_machine(10),
                            {"is_front": True}, 3)
    back = predict_intents(lambda: toadpole_machine(10),
                           {"is_front": False}, 3)
    assert front == ["buff: spikes 2 (Spiken)", "multi-attack 4x3 (SpikeSpit)",
                     "attack 8 (Whirl)"]
    assert back == ["attack 8 (Whirl)", "buff: spikes 2 (Spiken)",
                    "multi-attack 4x3 (SpikeSpit)"]
    assert predict_intents(seapunk_machine, {}, 3) == [
        "attack (SeaKick)", "multi-attack (SpinningKick)",
        "buff+block (BubbleBurp)"]


def test_random_monster_ai_confirmed_in_game():
    """RANDOM-AI VALIDATION (2026-07-09): Sean replayed ZPJHU3WSH2 fight 4
    (3 Two-Tailed Rats) and recorded intents turns 1-4. Observed exactly:
      t1 atk9|atk7|debuff (k=0), t2 debuff|atk9|atk9, t3 atk7|atk7|summon,
      t4 (new rat leftmost) atk7|atk9|debuff|atk9.
    Fit: MonsterAi counter 0 entering fight 4; starter IS logged (SL=Y);
    rolls in slot order L->R; the summoned rat's spawn-time roll (draw 7)
    is its next intent with NO re-roll; 10 draws total through turn 4."""
    from monster_ai import Rat
    from sts2_rng import Rng, RunRngSet

    rng = Rng(RunRngSet("ZPJHU3WSH2")["MonsterAi"].seed)
    rats = [Rat(i) for i in range(3)]          # k=0
    for r in rats:
        r.intent = r.starter
        r.log.append(r.starter)                # starter logged (confirmed)
    observed = [
        ["SCRATCH", "DISEASE_BITE", "SCREECH"],            # turn 1
        ["SCREECH", "SCRATCH", "SCRATCH"],                 # turn 2
        ["DISEASE_BITE", "DISEASE_BITE", "CALL_FOR_BACKUP"],  # turn 3
    ]
    assert [r.intent for r in rats] == observed[0]
    backup = 0
    for turn in (2, 3):
        for r in rats:
            if turn > 2:
                r.log.append(r.intent)
            if r.intent != "CALL_FOR_BACKUP":
                r.turns_until_summonable -= 1
        for r in rats:
            teammate = any(o is not r and o.intent == "CALL_FOR_BACKUP"
                           for o in rats)
            can = r.turns_until_summonable <= 0 and backup < 3 and not teammate
            r.intent = r.roll(rng, can)
        assert [r.intent for r in rats] == observed[turn - 1], f"turn {turn}"
    # turn-3 execution: two bites + the summon
    for r in rats:
        r.log.append(r.intent)
        if r.intent != "CALL_FOR_BACKUP":
            r.turns_until_summonable -= 1
        else:
            backup += 1
    new = Rat(-1)
    new.intent = new.roll(rng, can_summon=False)   # spawn roll = t4 intent
    new.log.append(new.intent)
    for r in rats:                                 # originals roll; slots full
        r.intent = r.roll(rng, can_summon=False)
    assert [new.intent] + [r.intent for r in rats] == \
        ["DISEASE_BITE", "SCRATCH", "SCREECH", "SCRATCH"]  # observed turn 4
    assert rng.counter == 10


def test_rng_validation_errors():
    rng = Rng(1)
    for bad in (lambda: rng.next_int(5, 5),
                lambda: rng.next_int(0),
                lambda: rng.fast_forward(-1)):
        try:
            bad()
        except ValueError:
            pass
        else:
            raise AssertionError("expected ValueError")


# ---------------------------------------------------------------------------
# v0.109 seeding scheme (#309) — ENGINE-PINNED
#
# Ground truth: the REAL engine (sts2.dll build v0.109.0, commit c12f634d)
# run headless via sim/v0.111.0/python/harness/probe_rng_seeding.py on 2026-07-16:
# fresh-boot RunRngSet/PlayerRngSet construction, first three NextInt(100)
# draws per stream. NEVER weaken these pins; they certify the v0.109 seed
# derivation (XxHash64 + 64-bit adds). The v0.108 tests above are untouched
# and pin the default (v0.108) scheme.
#
# Point-release validation: the probe was rerun against v0.109.1 commit
# c8c577f6 on 2026-07-26. All 70 pinned hash/run/player comparisons matched,
# and the relevant RNG CIL bodies were byte-identical to v0.109.0.
# ---------------------------------------------------------------------------

from sts2_rng import (  # noqa: E402
    GAME_BUILD_V0_108, GAME_BUILD_V0_109, deterministic_hash_code_v109,
    seeding_scheme, xxhash64,
)

V109 = GAME_BUILD_V0_109

# StringHelper.GetDeterministicHashCode (v0.109 = XXH64(UTF8, seed 0)),
# engine-observed:
V109_HASHES = {
    "up_front": 1912476647679082112,
    "shuffle": 3085484133485156116,
    "unknown_map_point": 10953017289181053782,
    "combat_card_generation": 11718963193360509838,
    "combat_potion_generation": 11431004730423270082,
    "combat_card_selection": 6098761115444869642,
    "combat_energy_costs": 12875475509260159103,
    "combat_targets": 6914754215372602050,
    "monster_ai": 6543427355376066983,
    "niche": 1662906298558773957,
    "combat_orbs": 10483575342834609490,
    "treasure_room_relics": 6791851140579503830,
    "rewards": 2374451800415955891,
    "shops": 15714054210322680683,
    "transformations": 13286249355281987573,
    "TESTBATCH0": 10072072574319474091,
    "ZPJHU3WSH2": 11137324208666220282,
    "8DVXPWUWRY": 2190969734833392909,
    "HQPAXCBS6P": 3190386984965681647,
    "": 17241709254077376921,
    "a": 15154266338359012955,
    "abc": 4952883123889572249,
}

# Fresh-boot first NextInt(100) x3 per run stream, engine-observed:
V109_RUN_DRAWS = {
    "TESTBATCH0": {
        "UpFront": [56, 1, 84], "Shuffle": [43, 99, 16],
        "UnknownMapPoint": [77, 86, 57],
        "CombatCardGeneration": [3, 81, 10],
        "CombatPotionGeneration": [75, 27, 7],
        "CombatCardSelection": [50, 59, 14],
        "CombatEnergyCosts": [48, 65, 28], "CombatTargets": [22, 25, 20],
        "MonsterAi": [20, 58, 89], "Niche": [90, 10, 56],
        "CombatOrbs": [82, 6, 84], "TreasureRoomRelics": [46, 52, 11],
    },
    "ZPJHU3WSH2": {
        "UpFront": [64, 63, 13], "Shuffle": [87, 89, 72],
        "UnknownMapPoint": [48, 91, 31],
        "CombatCardGeneration": [82, 1, 39],
        "CombatPotionGeneration": [11, 31, 90],
        "CombatCardSelection": [49, 19, 13],
        "CombatEnergyCosts": [85, 27, 9], "CombatTargets": [64, 86, 25],
        "MonsterAi": [43, 82, 55], "Niche": [97, 99, 22],
        "CombatOrbs": [22, 68, 79], "TreasureRoomRelics": [51, 73, 65],
    },
    # legacy escape: "old" prefix -> old djb2 hash of the remainder
    "oldZPJHU3WSH2": {
        "UpFront": [74, 39, 69], "Shuffle": [14, 37, 47],
        "UnknownMapPoint": [29, 72, 46],
        "CombatCardGeneration": [4, 62, 31],
        "CombatPotionGeneration": [21, 97, 40],
        "CombatCardSelection": [23, 51, 10],
        "CombatEnergyCosts": [73, 94, 23], "CombatTargets": [33, 37, 56],
        "MonsterAi": [90, 41, 49], "Niche": [17, 13, 71],
        "CombatOrbs": [34, 68, 2], "TreasureRoomRelics": [93, 5, 41],
    },
}

# Fresh-boot first NextInt(100) x3 per player stream, engine-observed:
V109_PLAYER_DRAWS = {
    ("TESTBATCH0", 0): {"Rewards": [50, 37, 37], "Shops": [80, 44, 4],
                        "Transformations": [23, 84, 98]},
    ("TESTBATCH0", 1): {"Rewards": [79, 92, 97], "Shops": [14, 66, 66],
                        "Transformations": [22, 81, 37]},
    ("ZPJHU3WSH2", 0): {"Rewards": [63, 27, 57], "Shops": [32, 99, 69],
                        "Transformations": [4, 37, 75]},
    ("ZPJHU3WSH2", 1): {"Rewards": [60, 6, 26], "Shops": [27, 30, 92],
                        "Transformations": [89, 83, 63]},
}


def test_xxh64_reference_vectors():
    # canonical XXH64 spec vectors (independent of the game)
    assert xxhash64(b"", 0) == 0xEF46DB3751D8E999
    assert xxhash64(b"a", 0) == V109_HASHES["a"]
    assert xxhash64(b"abc", 0) == V109_HASHES["abc"]
    # >=32-byte input exercises the lane loop
    assert xxhash64(b"combat_potion_generation_padding", 0) == \
        xxhash64(b"combat_potion_generation_padding")


def test_v109_hash_matches_engine():
    for s, expected in V109_HASHES.items():
        assert deterministic_hash_code_v109(s) == expected, repr(s)


def test_v109_run_set_seed_derivation():
    rs = RunRngSet("ZPJHU3WSH2", build=V109)
    assert rs.seed == V109_HASHES["ZPJHU3WSH2"]
    for name in RUN_RNG_STREAMS:
        expected = (rs.seed
                    + V109_HASHES[snake_case(name)]) & 0xFFFFFFFFFFFFFFFF
        assert rs[name].seed == expected, name


def test_v109_old_prefix_uses_legacy_hash():
    # RunRngSet::.ctor (v0.109, RVA 0x50f70): "old"-prefixed seed strings
    # hash the remainder with GetDeterministicHashCodeOld, zero-extended.
    rs = RunRngSet("oldZPJHU3WSH2", build=V109)
    assert rs.seed == deterministic_hash_code("ZPJHU3WSH2") & 0xFFFFFFFF \
        == 1584024330
    # ... but the per-stream name hash is still XxHash64:
    assert rs["Shuffle"].seed == \
        (1584024330 + V109_HASHES["shuffle"]) & 0xFFFFFFFFFFFFFFFF


def test_v109_run_streams_match_engine():
    for seed_string, streams in V109_RUN_DRAWS.items():
        rs = RunRngSet(seed_string, build=V109)
        for name, expected in streams.items():
            got = [rs[name].next_int(100) for _ in range(3)]
            assert got == expected, (seed_string, name, got)


def test_v109_player_streams_match_engine():
    for (seed_string, slot), streams in V109_PLAYER_DRAWS.items():
        ps = PlayerRngSet(seed_string, slot, build=V109)
        assert ps.seed == \
            (V109_HASHES[seed_string] + slot) & 0xFFFFFFFFFFFFFFFF
        for name, expected in streams.items():
            got = [ps[name].next_int(100) for _ in range(3)]
            assert got == expected, (seed_string, slot, name, got)


def test_v109_counters_fast_forward():
    # counter semantics are scheme-independent
    rs = RunRngSet("TESTBATCH0", build=V109)
    first3 = [rs["Shuffle"].next_int(100) for _ in range(3)]
    rs_ff = RunRngSet("TESTBATCH0", {"Shuffle": 2}, build=V109)
    assert rs_ff["Shuffle"].next_int(100) == first3[2]


def test_v109_organic_midrun_save_matches_all_serialized_stream_states():
    """#309 human item: end-to-end v19 save certification, 12/12.

    Unlike the fresh-boot engine vectors above, this fixture fast-forwards
    roughly 800 mixed organic draws and compares the game's own serialized
    xoshiro state, not merely a converted output value.
    """
    pin = V109_MIDRUN_PIN
    assert pin["build"] == V109 and pin["seed"] == "MPXVZK1KFG4Z"
    counters = {
        name: pin["streams"][snake_case(name)]["counter"]
        for name in RUN_RNG_STREAMS
    }
    rs = RunRngSet(pin["seed"], counters, build=pin["build"])
    assert set(pin["streams"]) == {
        snake_case(name) for name in RUN_RNG_STREAMS}
    for name in RUN_RNG_STREAMS:
        expected = pin["streams"][snake_case(name)]
        actual = rs[name]
        assert actual.counter == expected["counter"], name
        assert [actual._random.s0, actual._random.s1,
                actual._random.s2, actual._random.s3] == \
            expected["state"], name


def test_v109_point_release_uses_verified_scheme():
    assert seeding_scheme("v0.109.1") == "v109"


def test_v110_1_uses_engine_verified_v109_scheme():
    # Batch 202 / #793: 267 scalar engine comparisons matched exactly.
    assert seeding_scheme("v0.110.1") == "v109"


def test_v111_0_uses_engine_verified_v109_scheme():
    # Batch 293 / #1214: 267 scalar and 42 Encounter observations matched.
    assert GAME_BUILD_V0_111_0 == "v0.111.0"
    assert seeding_scheme(GAME_BUILD_V0_111_0) == "v109"
    assert seeding_scheme("  v0.111.0  ") == "v109"


def test_default_build_is_v108():
    # Every pre-#309 pin constructed RunRngSet(seed) with no build arg;
    # the default MUST stay on the v0.108 scheme.
    assert RunRngSet("ZPJHU3WSH2").seed == \
        RunRngSet("ZPJHU3WSH2", build=GAME_BUILD_V0_108).seed == 1584024330
    assert seeding_scheme(GAME_BUILD_V0_108) == "v108"
    assert seeding_scheme(GAME_BUILD_V0_109) == "v109"
    # v0.107.2 used to resolve to "v108" by range. It refuses now (#1265):
    # the v108 derivation was verified at v0.108.0 and nowhere below it, so
    # every earlier build was getting a scheme by extrapolation -- including
    # all 355 runs in the local corpus.
    with pytest.raises(NotImplementedError):
        seeding_scheme("v0.107.2")


def test_unknown_future_build_refuses():
    # I5: a build whose seeding has not been re-verified must refuse.
    for bad in ("v0.110.0", "v0.110.2", "v0.111.1", "v0.112.0",
                "v1.0.0", "garbage"):
        try:
            seeding_scheme(bad)
        except NotImplementedError:
            pass
        else:
            raise AssertionError(f"{bad} did not refuse")


if __name__ == "__main__":
    failed = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"PASS {name}")
            except AssertionError as e:
                failed += 1
                print(f"FAIL {name}: {e}")
    sys.exit(1 if failed else 0)
